<?php

declare(strict_types=1);

namespace Pulsar\Extension\Cms\Docs;

use Pulsar\Api\Api;

use function mb_strtolower;
use function preg_match_all;
use function preg_replace;
use function strip_tags;
use function trim;

use const PREG_SET_ORDER;

/**
 * Extracts a table of contents from rendered HTML headings.
 *
 * Scans for H2 and H3 elements, using their `id` attribute as the
 * anchor. When a heading lacks an `id`, one is generated by slugifying
 * the heading text.
 */
#[Api(since: '1.0.0')]
final class TocExtractor
{
    /**
     * Extract table of contents entries from rendered HTML.
     *
     * @return list<array{level: int, id: string, text: string}>
     */
    public static function extract(string $html): array
    {
        $entries = [];

        preg_match_all(
            '/<h([23])(?:\s+id="([^"]*)")?[^>]*>(.*?)<\/h[23]>/si',
            $html,
            $matches,
            PREG_SET_ORDER,
        );

        foreach ($matches as $match) {
            $level = (int) $match[1];
            $text = strip_tags($match[3]);
            $id = $match[2] !== '' ? $match[2] : self::slugify($text);

            $entries[] = ['level' => $level, 'id' => $id, 'text' => $text];
        }

        return $entries;
    }

    private static function slugify(string $text): string
    {
        $slug = mb_strtolower($text);
        $slug = (string) preg_replace('/[^a-z0-9]+/', '-', $slug);

        return trim($slug, '-');
    }
}
