<?php

declare(strict_types=1);

namespace Pulsar\Console\Command\NewProject;

use NoDiscard;
use Pulsar\Api\Api;

/**
 * Application preset for new project scaffolding.
 *
 * Determines the initial directory layout, configuration files,
 * and boilerplate code generated by `pulsar new`.
 * @api
 */
#[Api(since: '1.0.0')]
enum ProjectPreset: string
{
    /** Bare kernel with a single hello route. */
    case Minimal = 'minimal';

    /** Full web stack: sessions, CSRF protection, view templates. */
    case Web = 'web';

    /** JSON-focused API: no sessions, structured error responses. */
    case Api = 'api';

    /**
     * Resolve a preset from user input, defaulting to Web.
     */
    #[NoDiscard]
    public static function fromInput(?string $value): self
    {
        if ($value === null || $value === '') {
            return self::Web;
        }

        return self::tryFrom($value) ?? self::Web;
    }
}
