<?php

declare(strict_types=1);

namespace Pulsar\Deploy\Snippet;

use Pulsar\Api\Internal;
use Pulsar\Config\DeployConfig;

use function implode;
use function sprintf;

/**
 * Generates a vendor-neutral reverse proxy configuration snippet.
 *
 * The output is a generic, commented configuration that can be adapted
 * to any reverse proxy or load balancer. No vendor product names are used.
 */
#[Internal]
final class ProxySnippetGenerator
{
    /**
     * Generate a reverse proxy configuration snippet based on deploy settings.
     */
    public function generate(DeployConfig $config): string
    {
        $lines = [];

        $lines[] = '# Reverse Proxy Configuration Snippet';
        $lines[] = '# Generated by Pulsar deploy:check — adapt to your proxy software.';
        $lines[] = '#';
        $lines[] = '# This is a reference template. Review and adjust values for your environment.';
        $lines[] = '';

        // Trusted proxy headers
        $lines[] = '# --- Trusted Proxy Headers ---';
        $lines[] = '# Forward these headers from the proxy to the application:';
        $lines[] = '#   X-Forwarded-For    — Client IP address';
        $lines[] = '#   X-Forwarded-Proto  — Original protocol (http/https)';
        $lines[] = '#   X-Forwarded-Host   — Original Host header';
        $lines[] = '#   X-Forwarded-Port   — Original port';
        $lines[] = '';

        if ($config->trustedProxies !== []) {
            $lines[] = '# Trusted proxy source addresses:';

            foreach ($config->trustedProxies as $proxy) {
                $lines[] = sprintf('#   allow %s;', $proxy);
            }
        } else {
            $lines[] = '# No trusted proxies configured.';
            $lines[] = '# Add proxy IP addresses or CIDR ranges to config/deploy.php.';
        }

        $lines[] = '';

        // Request size limits
        $lines[] = '# --- Request Size Limits ---';
        $lines[] = sprintf('# Maximum POST body size: %dMB', $config->maxPostSizeMb);
        $lines[] = sprintf('#   client_max_body_size %dm;', $config->maxPostSizeMb);
        $lines[] = '';
        $lines[] = sprintf('# Maximum upload size: %dMB', $config->maxUploadSizeMb);
        $lines[] = sprintf('#   client_max_upload_size %dm;', $config->maxUploadSizeMb);
        $lines[] = '';

        // Timeouts
        $lines[] = '# --- Timeouts ---';
        $lines[] = '# Adjust these based on your application response time requirements.';
        $lines[] = '#   proxy_connect_timeout 5s;';
        $lines[] = '#   proxy_read_timeout    60s;';
        $lines[] = '#   proxy_send_timeout    60s;';
        $lines[] = '';

        // Buffering
        $lines[] = '# --- Proxy Buffering ---';
        $lines[] = '# Enable buffering to reduce backend load.';
        $lines[] = '#   proxy_buffering on;';
        $lines[] = '#   proxy_buffer_size 4k;';
        $lines[] = '#   proxy_buffers 8 4k;';
        $lines[] = '';

        // Health check endpoint
        $lines[] = '# --- Health Check ---';
        $lines[] = '# Configure your proxy to poll the health endpoint:';
        $lines[] = '#   health_check uri=/health interval=10s;';

        return implode("\n", $lines) . "\n";
    }
}
