<?php

declare(strict_types=1);

namespace Pulsar\Deploy\Snippet;

use Pulsar\Api\Internal;

use function implode;

/**
 * Generates a vendor-neutral TLS configuration snippet.
 *
 * The output is a generic, commented configuration for TLS termination
 * that can be adapted to any web server or proxy. No vendor product names are used.
 */
#[Internal]
final class TlsSnippetGenerator
{
    /**
     * Generate a TLS configuration snippet.
     *
     * @param bool $http3 Whether to include HTTP/3 (QUIC) Alt-Svc configuration
     */
    public function generate(bool $http3 = false): string
    {
        $lines = [];

        $lines[] = '# TLS Configuration Snippet';
        $lines[] = '# Generated by Pulsar deploy:check: adapt to your web server or proxy.';
        $lines[] = '#';
        $lines[] = '# This is a reference template. Review and adjust for your environment.';
        $lines[] = '';

        // Protocol versions
        $lines[] = '# --- TLS Protocol Versions ---';
        $lines[] = '# Minimum TLS 1.2, prefer TLS 1.3 when available.';
        $lines[] = '#   ssl_protocols TLSv1.2 TLSv1.3;';
        $lines[] = '';

        // Cipher suites
        $lines[] = '# --- Cipher Suites ---';
        $lines[] = '# TLS 1.3 cipher suites (server preference):';
        $lines[] = '#   TLS_AES_256_GCM_SHA384';
        $lines[] = '#   TLS_CHACHA20_POLY1305_SHA256';
        $lines[] = '#   TLS_AES_128_GCM_SHA256';
        $lines[] = '#';
        $lines[] = '# TLS 1.2 cipher suites (ECDHE only, AEAD modes):';
        $lines[] = '#   ECDHE-ECDSA-AES256-GCM-SHA384';
        $lines[] = '#   ECDHE-RSA-AES256-GCM-SHA384';
        $lines[] = '#   ECDHE-ECDSA-CHACHA20-POLY1305';
        $lines[] = '#   ECDHE-RSA-CHACHA20-POLY1305';
        $lines[] = '#   ECDHE-ECDSA-AES128-GCM-SHA256';
        $lines[] = '#   ECDHE-RSA-AES128-GCM-SHA256';
        $lines[] = '#';
        $lines[] = '#   ssl_prefer_server_ciphers on;';
        $lines[] = '';

        // HSTS
        $lines[] = '# --- HSTS (HTTP Strict Transport Security) ---';
        $lines[] = '# Instruct browsers to always use HTTPS for this domain.';
        $lines[] = '#   add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;';
        $lines[] = '';

        // OCSP Stapling
        $lines[] = '# --- OCSP Stapling ---';
        $lines[] = '# Enable OCSP stapling to improve TLS handshake performance';
        $lines[] = '# and reduce reliance on CA responder availability.';
        $lines[] = '#   ssl_stapling on;';
        $lines[] = '#   ssl_stapling_verify on;';
        $lines[] = '#   ssl_trusted_certificate /path/to/chain.pem;';
        $lines[] = '';

        // Session resumption
        $lines[] = '# --- Session Resumption ---';
        $lines[] = '# Enable session tickets for faster reconnections.';
        $lines[] = '#   ssl_session_cache shared:TLS:10m;';
        $lines[] = '#   ssl_session_timeout 1d;';
        $lines[] = '#   ssl_session_tickets on;';
        $lines[] = '';

        // Certificate
        $lines[] = '# --- Certificate ---';
        $lines[] = '#   ssl_certificate     /path/to/fullchain.pem;';
        $lines[] = '#   ssl_certificate_key /path/to/privkey.pem;';

        if ($http3) {
            $lines[] = '';
            $lines[] = '# --- HTTP/3 (QUIC) ---';
            $lines[] = '# Advertise HTTP/3 availability via the Alt-Svc header.';
            $lines[] = '# Ensure UDP port 443 is open in your firewall.';
            $lines[] = '#   add_header Alt-Svc \'h3=":443"; ma=86400\' always;';
            $lines[] = '#';
            $lines[] = '# Listen on QUIC (UDP):';
            $lines[] = '#   listen 443 quic reuseport;';
            $lines[] = '#   listen [::]:443 quic reuseport;';
            $lines[] = '#';
            $lines[] = '# QUIC-specific settings:';
            $lines[] = '#   quic_retry on;';
            $lines[] = '#   ssl_early_data on;';
        }

        return implode("\n", $lines) . "\n";
    }
}
