[package]
name = "pulsar-graphql"
description = "GraphQL on async-graphql with Dataloader, subscriptions, query cost analysis."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-api = { path = "../pulsar-api", version = "=0.0.1-alpha.0" }
pulsar-websocket = { path = "../pulsar-websocket", version = "=0.0.1-alpha.0" }
async-graphql = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
