<?php

declare(strict_types=1);

namespace Pulsar\Tests\Unit\Console\Command\Dev;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Pulsar\Console\Command\Dev\ComposeFileGenerator;
use Pulsar\Console\Command\Dev\DevConfig;

#[CoversClass(ComposeFileGenerator::class)]
final class ComposeFileGeneratorTest extends TestCase
{
    #[Test]
    public function generateWithDefaultConfig(): void
    {
        $config = new DevConfig();
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringContainsString('services:', $output);
        self::assertStringContainsString('app:', $output);
        self::assertStringContainsString('postgres:', $output);
        self::assertStringContainsString('redis:', $output);
        self::assertStringContainsString('mailpit:', $output);
        self::assertStringContainsString('volumes:', $output);
        self::assertStringContainsString('db-data:', $output);
        self::assertStringContainsString('redis-data:', $output);
    }

    #[Test]
    public function generateWithMysql(): void
    {
        $config = new DevConfig(database: 'mysql', dbPort: 3306);
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringContainsString('mysql:', $output);
        self::assertStringNotContainsString('postgres:', $output);
        self::assertStringContainsString('MYSQL_DATABASE: pulsar', $output);
        self::assertStringContainsString('MYSQL_ROOT_PASSWORD: secret', $output);
        self::assertStringContainsString('DB_HOST: mysql', $output);
    }

    #[Test]
    public function generateWithSqliteOmitsDatabaseService(): void
    {
        $config = new DevConfig(database: 'sqlite');
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringNotContainsString('postgres:', $output);
        self::assertStringNotContainsString('mysql:', $output);
        self::assertStringContainsString('DB_DRIVER: sqlite', $output);
        self::assertStringNotContainsString('db-data:', $output);
    }

    #[Test]
    public function generateWithoutRedis(): void
    {
        $config = new DevConfig(redis: false);
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringNotContainsString('redis:', $output);
        self::assertStringNotContainsString('REDIS_HOST', $output);
        self::assertStringNotContainsString('redis-data:', $output);
    }

    #[Test]
    public function generateWithoutMailpit(): void
    {
        $config = new DevConfig(mailpit: false);
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringNotContainsString('mailpit:', $output);
        self::assertStringNotContainsString('MAIL_HOST', $output);
    }

    #[Test]
    public function generateRespectsCustomPorts(): void
    {
        $config = new DevConfig(
            appPort: 9090,
            dbPort: 5433,
            redisPort: 6380,
            mailpitSmtpPort: 2025,
            mailpitWebPort: 9025,
        );

        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringContainsString('"9090:8080"', $output);
        self::assertStringContainsString('"5433:5432"', $output);
        self::assertStringContainsString('"6380:6379"', $output);
        self::assertStringContainsString('"2025:1025"', $output);
        self::assertStringContainsString('"9025:8025"', $output);
    }

    #[Test]
    public function generateIncludesHealthchecks(): void
    {
        $config = new DevConfig();
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringContainsString('healthcheck:', $output);
        self::assertStringContainsString('pg_isready', $output);
        self::assertStringContainsString('redis-cli', $output);
    }

    #[Test]
    public function generateIncludesDependsOnWithHealthCondition(): void
    {
        $config = new DevConfig();
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringContainsString('depends_on:', $output);
        self::assertStringContainsString('condition: service_healthy', $output);
    }

    #[Test]
    public function generateIncludesCommentHeader(): void
    {
        $config = new DevConfig();
        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringStartsWith('# Generated by Pulsar dev:start', $output);
    }

    #[Test]
    public function generateMinimalSqliteNoRedisNoMailpit(): void
    {
        $config = new DevConfig(
            database: 'sqlite',
            redis: false,
            mailpit: false,
        );

        $generator = new ComposeFileGenerator($config);
        $output = $generator->generate();

        self::assertStringContainsString('app:', $output);
        self::assertStringNotContainsString('postgres:', $output);
        self::assertStringNotContainsString('mysql:', $output);
        self::assertStringNotContainsString('redis:', $output);
        self::assertStringNotContainsString('mailpit:', $output);
        self::assertStringNotContainsString('depends_on:', $output);
        // No top-level volumes section when only app service (no db-data or redis-data)
        self::assertStringNotContainsString('db-data:', $output);
        self::assertStringNotContainsString('redis-data:', $output);
    }
}
