<?php

declare(strict_types=1);

namespace Pulsar\Extension\Compiler;

use Pulsar\Api\Internal;
use Pulsar\Extensibility\Exception\DependencyException;
use Pulsar\Extensibility\ExtensionManifest;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

use function array_filter;
use function array_keys;
use function array_shift;
use function array_values;
use function count;
use function file_get_contents;
use function hash;
use function hash_final;
use function hash_init;
use function hash_update;
use function in_array;
use function is_dir;
use function ksort;
use function sort;
use function str_replace;
use function strcmp;
use function var_export;

use const DIRECTORY_SEPARATOR;
use const SORT_STRING;

/**
 * Build-time compiler that resolves extension dependency graphs into a deterministic manifest.
 *
 * Performs topological sorting with deterministic tie-breaking (alphabetical by name)
 * and computes content hashes for config schemas and extension source code.
 */
#[Internal]
final class ExtensionGraphCompiler
{
    /**
     * Compile a list of extension manifests into a deterministic compiled manifest.
     *
     * @param list<ExtensionManifest> $manifests
     * @param list<string> $disabledExtensions Extension names to mark as disabled
     * @throws DependencyException If circular dependencies are detected or dependencies are missing
     */
    public function compile(array $manifests, array $disabledExtensions = []): CompiledExtensionManifest
    {
        $byName = $this->buildLookup($manifests);
        $this->validateDependencies($manifests, $byName);
        $sorted = $this->topologicalSort($manifests, $byName);

        $entries = [];
        $configHashes = [];
        $codeHashes = [];

        foreach ($sorted as $manifest) {
            $enabled = !in_array($manifest->name, $disabledExtensions, true);

            $entries[] = new CompiledExtensionEntry(
                name: $manifest->name,
                version: $manifest->version,
                extensionClass: $manifest->extensionClass,
                enabled: $enabled,
                dependencies: $manifest->getDependencies(),
                trustTier: $manifest->requestedTrustTier->value,
            );

            $configHashes[$manifest->name] = $this->hashConfigFiles($manifest->path);
            $codeHashes[$manifest->name] = $this->hashSourceFiles($manifest->path);
        }

        ksort($configHashes, SORT_STRING);
        ksort($codeHashes, SORT_STRING);

        $totalHash = CompiledExtensionManifest::computeTotalHash($configHashes, $codeHashes, $entries);

        return new CompiledExtensionManifest(
            extensions: $entries,
            configHashes: $configHashes,
            codeHashes: $codeHashes,
            totalHash: $totalHash,
        );
    }

    /**
     * Export a compiled manifest as PHP code returning the array.
     */
    public function export(CompiledExtensionManifest $manifest): string
    {
        $exported = var_export($manifest->toArray(), true);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by Pulsar ExtensionGraphCompiler. Do not edit.\nreturn " . $exported . ";\n";
    }

    /**
     * Build a name-indexed lookup map.
     *
     * @param list<ExtensionManifest> $manifests
     * @return array<string, ExtensionManifest>
     */
    private function buildLookup(array $manifests): array
    {
        $byName = [];

        foreach ($manifests as $manifest) {
            $byName[$manifest->name] = $manifest;
        }

        return $byName;
    }

    /**
     * Validate that all declared dependencies exist in the manifest set.
     *
     * @param list<ExtensionManifest> $manifests
     * @param array<string, ExtensionManifest> $byName
     * @throws DependencyException If a required dependency is missing
     */
    private function validateDependencies(array $manifests, array $byName): void
    {
        foreach ($manifests as $manifest) {
            foreach ($manifest->getDependencies() as $dependency) {
                if (!isset($byName[$dependency])) {
                    throw DependencyException::missingDependency($manifest->name, $dependency);
                }
            }
        }
    }

    /**
     * Topological sort with deterministic tie-breaking by extension name.
     *
     * Uses Kahn's algorithm. When multiple extensions have in-degree zero simultaneously,
     * they are processed in alphabetical order for deterministic output.
     *
     * @param list<ExtensionManifest> $manifests
     * @param array<string, ExtensionManifest> $byName
     * @return list<ExtensionManifest>
     * @throws DependencyException If circular dependency detected
     */
    private function topologicalSort(array $manifests, array $byName): array
    {
        $inDegree = [];
        $dependents = [];

        foreach ($manifests as $manifest) {
            $name = $manifest->name;
            $inDegree[$name] ??= 0;
            $dependents[$name] ??= [];

            foreach ($manifest->getDependencies() as $dependency) {
                $inDegree[$name]++;
                $dependents[$dependency][] = $name;
            }
        }

        // Collect initial zero-degree nodes and sort alphabetically
        $queue = [];
        foreach ($manifests as $manifest) {
            if ($inDegree[$manifest->name] === 0) {
                $queue[] = $manifest->name;
            }
        }
        sort($queue, SORT_STRING);

        $sorted = [];
        $visited = 0;

        while ($queue !== []) {
            $current = array_shift($queue);
            $sorted[] = $byName[$current];
            $visited++;

            // Collect newly freed nodes
            $newlyFreed = [];
            foreach ($dependents[$current] as $dependent) {
                $inDegree[$dependent]--;
                if ($inDegree[$dependent] === 0) {
                    $newlyFreed[] = $dependent;
                }
            }

            // Sort newly freed nodes and merge into queue, maintaining sorted order
            if ($newlyFreed !== []) {
                sort($newlyFreed, SORT_STRING);
                $queue = $this->mergeSorted($queue, $newlyFreed);
            }
        }

        if ($visited !== count($manifests)) {
            $remaining = array_values(array_filter(
                array_keys($inDegree),
                static fn(string $name): bool => !in_array($byName[$name], $sorted, true),
            ));
            sort($remaining, SORT_STRING);
            throw DependencyException::circularDependency($remaining);
        }

        return $sorted;
    }

    /**
     * Merge two sorted string arrays into a single sorted array.
     *
     * @param list<string> $a
     * @param list<string> $b
     * @return list<string>
     */
    private function mergeSorted(array $a, array $b): array
    {
        $result = [];
        $i = 0;
        $j = 0;
        $lenA = count($a);
        $lenB = count($b);

        while ($i < $lenA && $j < $lenB) {
            $valA = $a[$i];
            $valB = $b[$j];
            if (strcmp($valA, $valB) <= 0) {
                $result[] = $valA;
                $i++;
            } else {
                $result[] = $valB;
                $j++;
            }
        }

        while ($i < $lenA) {
            $result[] = $a[$i];
            $i++;
        }

        while ($j < $lenB) {
            $result[] = $b[$j];
            $j++;
        }

        return $result;
    }

    /**
     * Compute SHA-256 hash of all config files for an extension.
     *
     * Hashes files in {extensionPath}/config/*.php, sorted by normalized path for determinism.
     */
    private function hashConfigFiles(string $extensionPath): string
    {
        $configDir = $extensionPath . '/config';

        if (!is_dir($configDir)) {
            return hash('sha256', '');
        }

        return $this->hashDirectory($configDir);
    }

    /**
     * Compute SHA-256 hash of all source files for an extension.
     *
     * Hashes files in {extensionPath}/src/**\/*.php, sorted by normalized path for determinism.
     */
    private function hashSourceFiles(string $extensionPath): string
    {
        $srcDir = $extensionPath . '/src';

        if (!is_dir($srcDir)) {
            return hash('sha256', '');
        }

        return $this->hashDirectory($srcDir);
    }

    /**
     * Hash all PHP files in a directory tree deterministically.
     *
     * Files are sorted by their normalized (forward-slash) paths before hashing
     * to ensure consistent output across platforms.
     */
    private function hashDirectory(string $directory): string
    {
        $files = [];
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($directory),
        );

        /** @var SplFileInfo $file */
        foreach ($iterator as $file) {
            if (!$file->isFile()) {
                continue;
            }

            if ($file->getExtension() !== 'php') {
                continue;
            }

            $normalizedPath = str_replace(DIRECTORY_SEPARATOR, '/', $file->getPathname());
            $files[$normalizedPath] = $file->getPathname();
        }

        ksort($files, SORT_STRING);

        $context = hash_init('sha256');

        foreach ($files as $normalizedPath => $realPath) {
            hash_update($context, $normalizedPath);
            $content = file_get_contents($realPath);
            if ($content !== false) {
                hash_update($context, $content);
            }
        }

        return hash_final($context);
    }
}
