<?php

declare(strict_types=1);

namespace Pulsar\Event\Internal;

use Closure;
use Pulsar\Api\Internal;
use Pulsar\Event\Exception\EventException;

use function array_unique;
use function array_values;
use function is_array;
use function is_object;
use function is_string;
use function preg_match;
use function sprintf;
use function strlen;
use function var_export;

/**
 * Build-time compiler: generates a compiled listener map from a ListenerProvider.
 *
 * Performs mandatory naming discipline lint on all event class names.
 * Violations halt the build (no opt-out mechanism).
 */
#[Internal]
final class EventMapCompiler
{
    private const int MAX_LABEL_LENGTH = 255;

    /**
     * Compile a ListenerProvider into a serializable map.
     *
     * @return array<class-string, array{listeners: list<array{class: string, method: string, priority: int, moduleId: string}>, requiresEnvelope: bool, stormOverride: ?int, listenerModuleIds: list<string>}>
     *
     * @throws EventException On naming discipline violations
     */
    public function compile(ListenerProvider $provider): array
    {
        $map = [];

        foreach ($provider->registeredEventClasses() as $eventClass) {
            $this->validateEventClassName($eventClass);

            $rawListeners = $provider->rawListenersFor($eventClass);
            $compiledListeners = [];
            $moduleIds = [];

            foreach ($rawListeners as $entry) {
                $parsed = $this->parseListenerCallable($entry['callable']);
                $compiledListeners[] = [
                    'class' => $parsed['class'],
                    'method' => $parsed['method'],
                    'priority' => $entry['priority'],
                    'moduleId' => $entry['moduleId'],
                ];

                if ($entry['moduleId'] !== '') {
                    $moduleIds[] = $entry['moduleId'];
                }
            }

            $moduleIds = array_values(array_unique($moduleIds));

            $map[$eventClass] = [
                'listeners' => $compiledListeners,
                'requiresEnvelope' => $provider->requiresEnvelopeFor($eventClass),
                'stormOverride' => $provider->stormOverrideFor($eventClass),
                'listenerModuleIds' => $moduleIds,
            ];
        }

        return $map;
    }

    /**
     * Export a compiled map as PHP code returning the array.
     *
     * @param array<class-string, array{listeners: list<array{class: string, method: string, priority: int, moduleId: string}>, requiresEnvelope: bool, stormOverride: ?int, listenerModuleIds: list<string>}> $map
     */
    public function export(array $map): string
    {
        $exported = var_export($map, true);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by Pulsar EventMapCompiler. Do not edit.\nreturn " . $exported . ";\n";
    }

    /**
     * Validate an event class name against naming discipline rules.
     *
     * Mandatory, fail-hard, no opt-out:
     * - Max 255 characters
     * - ASCII alphanumeric + \ + _ only
     * - No PII-encoding patterns (emails, UUIDs, digit runs >8)
     *
     * @param class-string $className
     * @throws EventException On validation failure
     */
    private function validateEventClassName(string $className): void
    {
        if (strlen($className) > self::MAX_LABEL_LENGTH) {
            throw EventException::invalidEventClassName(
                $className,
                sprintf('exceeds maximum length of %d characters (%d)', self::MAX_LABEL_LENGTH, strlen($className)),
            );
        }

        // Allowed charset: ASCII alphanumeric + \ + _ only (rejects @, spaces, unicode, etc.)
        if (preg_match('/[^a-zA-Z0-9\\\\_]/', $className) === 1) {
            throw EventException::invalidEventClassName(
                $className,
                'contains disallowed characters (only ASCII alphanumeric, backslash, and underscore allowed)',
            );
        }

        // Reject UUID pattern (8-4-4-4-12 hex)
        if (preg_match('/[0-9a-fA-F]{8}[_\\\\][0-9a-fA-F]{4}[_\\\\][0-9a-fA-F]{4}[_\\\\][0-9a-fA-F]{4}[_\\\\][0-9a-fA-F]{12}/', $className) === 1) {
            throw EventException::invalidEventClassName($className, 'contains UUID-like pattern (possible PII encoding)');
        }

        // Reject digit runs >8 chars
        if (preg_match('/\d{9,}/', $className) === 1) {
            throw EventException::invalidEventClassName($className, 'contains digit run exceeding 8 characters (possible PII encoding)');
        }
    }

    /**
     * Parse a listener callable into class + method for compilation.
     *
     * @return array{class: string, method: string}
     */
    private function parseListenerCallable(callable $listener): array
    {
        if (is_array($listener)) {
            $target = $listener[0];
            $class = is_string($target) ? $target : $target::class;

            return ['class' => $class, 'method' => $listener[1]];
        }

        if (is_string($listener)) {
            return ['class' => $listener, 'method' => '__invoke'];
        }

        // For objects with __invoke
        if (is_object($listener) && !($listener instanceof Closure)) {
            return ['class' => $listener::class, 'method' => '__invoke'];
        }

        // Closures cannot be compiled; fail hard
        throw EventException::invalidListener('closures cannot be compiled; use an invokable class or [class, method] array');
    }
}
