<?php

declare(strict_types=1);

namespace Pulsar\Extension\DataAct\Mapping;

use Pulsar\Api\Internal;
use Pulsar\Compliance\Control;
use Pulsar\Compliance\ControlCatalog;
use Pulsar\Compliance\ControlStatus;

/**
 * Maps EU Data Act (Regulation 2023/2854) articles to Pulsar framework controls.
 *
 * Registers compliance controls that track which Data Act obligations
 * are covered by framework features across data holders, data recipients,
 * and cloud service providers.
 */
#[Internal(reason: 'Framework-internal control registration; use ControlCatalog for public access')]
final class DataActMapping
{
    /**
     * Register Data Act controls into the given catalog.
     */
    public static function register(ControlCatalog $catalog): void
    {
        // Art. 3-4: Data access rights for users
        $catalog->register(new Control(
            id: 'data-act-art-4',
            framework: 'data_act',
            title: 'Right to access data generated by connected products',
            description: 'Users have the right to access data generated by their use of a product '
                . 'or related service. Covered by DataPortabilityService and DataAccessController.',
            status: ControlStatus::Implemented,
            frameworkFeatures: ['data_portability_service', 'data_access_controller'],
        ));

        // Art. 5: Right to data portability
        $catalog->register(new Control(
            id: 'data-act-art-5',
            framework: 'data_act',
            title: 'Right to share data with third parties',
            description: 'Users may request the data holder to make data available to a third party. '
                . 'Data must be provided in a structured, commonly used, machine-readable format. '
                . 'Covered by ExportRequest and configurable export formats.',
            status: ControlStatus::Implemented,
            frameworkFeatures: ['export_request', 'data_portability_service'],
        ));

        // Art. 6: Third-party data access conditions
        $catalog->register(new Control(
            id: 'data-act-art-6',
            framework: 'data_act',
            title: 'Conditions for third-party data access',
            description: 'Data recipients must not use data for profiling, advertising, or purposes '
                . 'incompatible with the original purpose. Covered by ThirdPartyAccessPolicy '
                . 'purpose validation and denied-purpose list.',
            status: ControlStatus::Implemented,
            frameworkFeatures: ['third_party_access_policy', 'purpose_validation'],
        ));

        // Art. 23-26: Cloud switching and interoperability
        $catalog->register(new Control(
            id: 'data-act-art-25',
            framework: 'data_act',
            title: 'Cloud switching and transition period',
            description: 'Cloud providers must support customer switching with a maximum transition '
                . 'period, data export assistance, and functional equivalence. Covered by '
                . 'SwitchingAssistant and SwitchingPlan.',
            status: ControlStatus::Implemented,
            frameworkFeatures: ['switching_assistant', 'switching_plan'],
        ));

        // Art. 28-30: Interoperability requirements
        $catalog->register(new Control(
            id: 'data-act-art-28',
            framework: 'data_act',
            title: 'Interoperability specifications',
            description: 'Data processing services must publish interoperability specifications '
                . 'including supported formats, API standards, and open interfaces. Covered by '
                . 'InteroperabilityProfile.',
            status: ControlStatus::Implemented,
            frameworkFeatures: ['interoperability_profile', 'supported_formats'],
        ));

        // Art. 31: Essential requirements for smart contracts
        $catalog->register(new Control(
            id: 'data-act-art-31',
            framework: 'data_act',
            title: 'Smart contract essential requirements',
            description: 'Smart contracts for data sharing must ensure robustness, safe termination, '
                . 'data archiving, and access control. Framework provides the infrastructure; '
                . 'smart contract implementation is deployer responsibility.',
            status: ControlStatus::Partial,
            frameworkFeatures: ['data_access_controller', 'audit_logging'],
        ));
    }
}
