<?php

declare(strict_types=1);

namespace Pulsar\Extension\DataAct\Mapping;

use NoDiscard;
use Pulsar\Api\Internal;
use Pulsar\Compliance\ComplianceFramework;
use Pulsar\Compliance\Control\ControlDeclaration;
use Pulsar\Compliance\Control\ControlSubject;
use Pulsar\Compliance\Probe\AccessRestrictionProbe;

/**
 * Declares the EU Data Act controls Pulsar can be assessed against.
 *
 * Data access, sharing, cloud switching and interoperability are product and
 * contract obligations. Only the condition on third-party processing is enforced
 * by anything the framework can observe.
 */
#[Internal(reason: 'Framework-internal control declaration; the catalog is the public surface')]
final class DataActMapping
{
    /**
     * @return list<ControlDeclaration>
     */
    #[NoDiscard]
    public static function declarations(): array
    {
        return [
            ControlDeclaration::operatorResponsibility(
                id: 'data-act-art-4',
                framework: ComplianceFramework::DataAct,
                title: 'Right to access data generated by connected products',
                requirement: 'Where data cannot be directly accessed by the user from the connected '
                    . 'product, data holders shall make readily available data accessible to '
                    . 'the user without undue delay, free of charge and in a comprehensive, '
                    . 'structured, commonly used and machine-readable format (Article 4).',
                artefact: 'The user-facing access mechanism for product and related service data, '
                    . 'with the record of requests served.',
            ),

            ControlDeclaration::operatorResponsibility(
                id: 'data-act-art-5',
                framework: ComplianceFramework::DataAct,
                title: 'Right to share data with third parties',
                requirement: 'Upon request by a user, the data holder shall make available readily '
                    . 'available data to a third party without undue delay, of the same quality '
                    . 'as is available to the data holder (Article 5).',
                artefact: 'The third-party sharing mechanism and the record of user requests to '
                    . 'share data, with the recipients named.',
            ),

            ControlDeclaration::probed(
                id: 'data-act-art-6',
                framework: ComplianceFramework::DataAct,
                title: 'Conditions for third-party data access',
                requirement: 'A third party shall process the data made available to it only for the '
                    . 'purposes and under the conditions agreed with the user, and shall delete '
                    . 'it when no longer necessary (Article 6).',
                probe: new AccessRestrictionProbe(),
                subject: ControlSubject::AccessControl,
            ),

            ControlDeclaration::operatorResponsibility(
                id: 'data-act-art-25',
                framework: ComplianceFramework::DataAct,
                title: 'Cloud switching and transition period',
                requirement: 'Providers of data processing services shall include in contracts the '
                    . 'terms enabling a customer to switch to another provider or to '
                    . 'on-premises infrastructure, within a maximum transition period (Article '
                    . '25).',
                artefact: 'The cloud switching terms in the contract, with the transition plan and '
                    . 'the evidence of the maximum notice and transition periods offered.',
            ),

            ControlDeclaration::operatorResponsibility(
                id: 'data-act-art-28',
                framework: ComplianceFramework::DataAct,
                title: 'Interoperability specifications',
                requirement: 'Providers of data processing services shall make open interfaces '
                    . 'available and ensure compatibility with the interoperability '
                    . 'specifications or harmonised standards that apply (Article 28).',
                artefact: 'The interoperability specifications published for the service, and the '
                    . 'conformity statement against the applicable harmonised standards.',
            ),

            ControlDeclaration::operatorResponsibility(
                id: 'data-act-art-31',
                framework: ComplianceFramework::DataAct,
                title: 'Smart contract essential requirements',
                requirement: 'The vendor of a smart contract for executing a data sharing agreement '
                    . 'shall ensure it meets the essential requirements of robustness, safe '
                    . 'termination and interruption, data archiving and continuity, and access '
                    . 'control (Article 31).',
                artefact: 'The smart contract conformity assessment, covering robustness, safe '
                    . 'termination and the audit trail the Article requires.',
            ),
        ];
    }
}
