<?php

declare(strict_types=1);

namespace Pulsar\Http\Validation\Attribute;

use Pulsar\Api\Api;
use ReflectionAttribute;
use ReflectionClass;
use ReflectionProperty;

use function dirname;
use function file_put_contents;
use function is_dir;
use function mkdir;
use function var_export;

/**
 * Extracts #[Validate] and #[Sanitize] attributes from DTOs at build time.
 *
 * Produces a PHP array artifact that CompiledValidationMap loads at runtime
 * without reflection.
 * @api
 */
#[Api(since: '1.0.0')]
final readonly class ValidationCompiler
{
    /**
     * Compile validation metadata for the given classes into an artifact file.
     *
     * @param list<class-string> $classes
     */
    public function compile(array $classes, string $outputPath): void
    {
        $map = [];

        foreach ($classes as $class) {
            $reflection = new ReflectionClass($class);
            $rules = [];
            $filters = [];

            foreach ($reflection->getProperties(ReflectionProperty::IS_PUBLIC) as $property) {
                $propertyName = $property->getName();

                $validateAttributes = $property->getAttributes(
                    Validate::class,
                    ReflectionAttribute::IS_INSTANCEOF,
                );

                foreach ($validateAttributes as $attribute) {
                    /** @var Validate $validate */
                    $validate = $attribute->newInstance();
                    $rules[$propertyName][] = [
                        'rule' => $validate->rule,
                        'parameters' => $validate->parameters,
                        'groups' => $validate->groups,
                    ];
                }

                $sanitizeAttributes = $property->getAttributes(
                    Sanitize::class,
                    ReflectionAttribute::IS_INSTANCEOF,
                );

                foreach ($sanitizeAttributes as $attribute) {
                    /** @var Sanitize $sanitize */
                    $sanitize = $attribute->newInstance();
                    $filters[$propertyName][] = [
                        'filter' => $sanitize->filter,
                        'parameters' => $sanitize->parameters,
                    ];
                }
            }

            if ($rules !== [] || $filters !== []) {
                $map[$class] = [
                    'rules' => $rules,
                    'filters' => $filters,
                ];
            }
        }

        $dir = dirname($outputPath);

        if (!is_dir($dir)) {
            mkdir($dir, 0o755, true);
        }

        $exported = var_export($map, true);

        file_put_contents(
            $outputPath,
            "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by ValidationCompiler. Do not edit.\n\nreturn $exported;\n",
        );
    }
}
