[package]
name = "pulsar-edge"
description = "Edge compute (Cloudflare Workers, Fastly Compute) and ACME TLS provisioning."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-http = { path = "../pulsar-http", version = "=0.0.1-alpha.0" }
instant-acme = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
