<?php

declare(strict_types=1);

namespace Pulsar\Security\Vault;

use Pulsar\Api\Api;
use Pulsar\Security\Crypto\Encryptor;
use Pulsar\Security\Crypto\MasterKey;
use Pulsar\Security\Exception\SecurityException;
use SodiumException;

use function array_keys;
use function count;
use function dirname;
use function file_exists;
use function file_put_contents;
use function is_array;
use function is_string;
use function sprintf;
use function var_export;

/**
 * Encrypted secrets vault.
 *
 * Stores application secrets (API keys, credentials, DSN strings) encrypted
 * with the master key. Secrets are persisted to a PHP file that returns an
 * associative array of encrypted values.
 *
 * Usage:
 *   $vault = SecretVault::create($masterKey, 'config/secrets.encrypted.php');
 *   $vault->set('STRIPE_SECRET', 'sk_live_...');
 *   $value = $vault->get('STRIPE_SECRET');
 *
 * Sub-key ID 15 / context "secrets_" is used for vault encryption,
 * separate from the default encryption key.
 * @api
 */
#[Api(since: '1.0.0')]
final class SecretVault
{
    private const int VAULT_SUB_KEY_ID = 15;
    private const string VAULT_KDF_CONTEXT = 'secrets_';

    /** @var array<string, string> key => encrypted value */
    private array $secrets = [];
    private bool $loaded = false;

    private function __construct(
        private readonly Encryptor $encryptor,
        private readonly string $vaultPath,
    ) {}

    /**
     * Create a vault instance from a master key.
     *
     * @throws SodiumException
     */
    public static function create(MasterKey $masterKey, string $vaultPath): self
    {
        $encryptor = Encryptor::fromDerivedKey(
            $masterKey,
            self::VAULT_SUB_KEY_ID,
            self::VAULT_KDF_CONTEXT,
        );

        return new self($encryptor, $vaultPath);
    }

    /**
     * Store a secret value.
     *
     * @throws SecurityException If encryption fails
     */
    public function set(string $key, string $value): void
    {
        $this->ensureLoaded();
        $this->secrets[$key] = $this->encryptor->encrypt($value);
        $this->persist();
    }

    /**
     * Retrieve a decrypted secret value.
     *
     * @throws SecurityException If the key is not found or decryption fails
     */
    public function get(string $key): string
    {
        $this->ensureLoaded();

        if (!isset($this->secrets[$key])) {
            throw SecurityException::vaultKeyNotFound($key);
        }

        return $this->encryptor->decrypt($this->secrets[$key]);
    }

    /**
     * Check if a secret exists in the vault.
     */
    public function has(string $key): bool
    {
        $this->ensureLoaded();

        return isset($this->secrets[$key]);
    }

    /**
     * Remove a secret from the vault.
     */
    public function remove(string $key): void
    {
        $this->ensureLoaded();
        unset($this->secrets[$key]);
        $this->persist();
    }

    /**
     * List all secret keys (without decrypting values).
     *
     * @return list<string>
     */
    public function keys(): array
    {
        $this->ensureLoaded();

        return array_keys($this->secrets);
    }

    /**
     * Get the number of stored secrets.
     */
    public function count(): int
    {
        $this->ensureLoaded();

        return count($this->secrets);
    }

    private function ensureLoaded(): void
    {
        if ($this->loaded) {
            return;
        }

        $this->loaded = true;

        if (!file_exists($this->vaultPath)) {
            return;
        }

        /** @var mixed $data */
        $data = require $this->vaultPath;

        if (is_array($data)) {
            /** @var mixed $value */
            foreach ($data as $key => $value) {
                if (is_string($key) && is_string($value)) {
                    $this->secrets[$key] = $value;
                }
            }
        }
    }

    private function persist(): void
    {
        $exported = var_export($this->secrets, true);

        $content = sprintf(
            "<?php\n\ndeclare(strict_types=1);\n\n// This file is auto-generated by Pulsar SecretVault. Do not edit.\nreturn %s;\n",
            $exported,
        );

        // Vault directory must be owner-only: the file it contains holds
        // encrypted secrets (API keys, database credentials, PULSAR_MASTER_KEY).
        // World/group-readable permissions on the containing directory enable
        // local attackers to enumerate its contents even if the file itself
        // is restricted.
        $dir = dirname($this->vaultPath);

        if (!is_dir($dir)) {
            mkdir($dir, 0o700, true);
        }

        // Tighten directory permissions if a prior installation created it
        // with looser permissions.
        chmod($dir, 0o700);

        // Atomic write: write to a temp file under the same directory
        // (so the rename is an atomic filesystem operation on POSIX) then
        // swap it into place. This prevents partial-write corruption if
        // the process is killed mid-write.
        $tempFile = tempnam($dir, '.vault-');

        if ($tempFile === false) {
            throw SecurityException::encryptionFailed('unable to create temporary vault file');
        }

        $bytesWritten = file_put_contents($tempFile, $content, LOCK_EX);

        if ($bytesWritten === false) {
            unlink($tempFile);

            throw SecurityException::encryptionFailed('failed to write vault content');
        }

        // Owner-only read on the vault file
        chmod($tempFile, 0o600);

        if (!rename($tempFile, $this->vaultPath)) {
            unlink($tempFile);

            throw SecurityException::encryptionFailed('failed to swap vault file into place');
        }
    }
}
