<?php

declare(strict_types=1);

namespace Pulsar\Extension\Grpc\Manifest;

use NoDiscard;
use Pulsar\Api\Api;

use function array_map;
use function is_array;
use function is_string;
use function sprintf;
use function var_export;

/**
 * Compiled service manifest DTO.
 *
 * A build artifact consumed at boot time. Contains all registered gRPC
 * services and their method descriptors, serialized as a PHP array file
 * for zero-overhead loading.
 */
#[Api(since: '1.0.0')]
final readonly class ServiceManifest
{
    /**
     * @param list<ManifestEntry> $services  All registered service entries
     * @param string $version                Manifest format version
     * @param string $compiledAt             ISO 8601 compilation timestamp
     */
    public function __construct(
        public array $services,
        public string $version = '1.0',
        public string $compiledAt = '',
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    #[NoDiscard]
    public static function fromArray(array $data): self
    {
        /** @var list<array<string, mixed>> $servicesData */
        $servicesData = is_array($data['services'] ?? null) ? $data['services'] : [];

        $services = [];
        foreach ($servicesData as $entry) {
            if (is_array($entry)) {
                $services[] = ManifestEntry::fromArray($entry);
            }
        }

        return new self(
            services: $services,
            version: is_string($data['version'] ?? null) ? $data['version'] : '1.0',
            compiledAt: is_string($data['compiled_at'] ?? null) ? $data['compiled_at'] : '',
        );
    }

    /**
     * @return array{services: list<array{service_name: string, handler_class: string, methods: list<array{name: string, full_name: string, type: string, input_type: string, output_type: string, handler: string}>}>, version: string, compiled_at: string}
     */
    public function toArray(): array
    {
        return [
            'services' => array_map(
                static fn(ManifestEntry $entry): array => $entry->toArray(),
                $this->services,
            ),
            'version' => $this->version,
            'compiled_at' => $this->compiledAt,
        ];
    }

    /**
     * Generate a PHP array file string that returns the manifest data.
     *
     * The resulting file can be included with `require` for zero-overhead loading.
     */
    #[NoDiscard]
    public function toPhpArray(): string
    {
        $exported = var_export($this->toArray(), true);

        return sprintf(
            "<?php\n\ndeclare(strict_types=1);\n\n// Generated by Pulsar gRPC manifest compiler — do not edit.\n// Compiled at: %s\n\nreturn %s;\n",
            $this->compiledAt,
            $exported,
        );
    }
}
