<?php

declare(strict_types=1);

namespace Pulsar\Console\Command\Dev;

use Pulsar\Api\Internal;

use function implode;
use function sprintf;

/**
 * Generates docker-compose.yml content from DevConfig.
 */
#[Internal]
final readonly class ComposeFileGenerator
{
    private const string POSTGRES_IMAGE = 'postgres:17-alpine';
    private const string MYSQL_IMAGE = 'mysql:9.0';
    private const string REDIS_IMAGE = 'redis:7-alpine';
    private const string MAILPIT_IMAGE = 'axllent/mailpit:latest';

    public function __construct(
        private DevConfig $config,
    ) {}

    /**
     * Generate the full docker-compose.yml content.
     */
    public function generate(): string
    {
        $services = [];
        $volumes = [];

        $services[] = $this->appService();

        if ($this->config->requiresDatabaseContainer()) {
            $services[] = $this->databaseService();
            $volumes[] = $this->databaseVolume();
        }

        if ($this->config->redis) {
            $services[] = $this->redisService();
            $volumes[] = '  redis-data:';
        }

        if ($this->config->mailpit) {
            $services[] = $this->mailpitService();
        }

        $content = "# Generated by Pulsar dev:start: do not edit manually\n";
        $content .= "services:\n";
        $content .= implode("\n", $services);

        if ($volumes !== []) {
            $content .= "\n\nvolumes:\n";
            $content .= implode("\n", $volumes) . "\n";
        }

        return $content;
    }

    private function appService(): string
    {
        $lines = [
            '  app:',
            '    build:',
            '      context: .',
            '      dockerfile: Dockerfile',
            sprintf('      args:'),
            sprintf('        PHP_VERSION: "%s"', $this->config->phpVersion),
            sprintf('        MEMORY_LIMIT: "%dM"', $this->config->memoryLimit),
            sprintf('        XDEBUG: "%s"', $this->config->xdebug ? '1' : '0'),
        ];

        $lines[] = '    ports:';
        $lines[] = sprintf('      - "%d:8080"', $this->config->appPort);

        $lines[] = '    volumes:';
        $lines[] = '      - .:/app:cached';

        $lines[] = '    environment:';
        $lines[] = '      APP_ENV: development';

        if ($this->config->requiresDatabaseContainer()) {
            $driver = $this->config->database;
            $lines[] = sprintf('      DB_CONNECTION: %s', $driver);
            $lines[] = sprintf('      DB_HOST: %s', $driver === 'mysql' ? 'mysql' : 'postgres');
            $lines[] = '      DB_PORT: ' . ($driver === 'mysql' ? '3306' : '5432');
            $lines[] = '      DB_DATABASE: pulsar';
            $lines[] = '      DB_USERNAME: pulsar';
            $lines[] = '      DB_PASSWORD: secret';
        } else {
            $lines[] = '      DB_CONNECTION: sqlite';
            $lines[] = '      DB_DATABASE: /app/database/database.sqlite';
        }

        if ($this->config->redis) {
            $lines[] = '      REDIS_HOST: redis';
            $lines[] = '      REDIS_PORT: 6379';
        }

        if ($this->config->mailpit) {
            $lines[] = '      MAIL_HOST: mailpit';
            $lines[] = sprintf('      MAIL_PORT: %d', 1025);
        }

        $depends = [];

        if ($this->config->requiresDatabaseContainer()) {
            $depends[] = $this->config->database === 'mysql' ? 'mysql' : 'postgres';
        }

        if ($this->config->redis) {
            $depends[] = 'redis';
        }

        if ($depends !== []) {
            $lines[] = '    depends_on:';

            foreach ($depends as $dep) {
                $lines[] = sprintf('      %s:', $dep);
                $lines[] = '        condition: service_healthy';
            }
        }

        $lines[] = '    healthcheck:';
        $lines[] = '      test: ["CMD", "php", "-r", "echo 1;"]';
        $lines[] = '      interval: 10s';
        $lines[] = '      timeout: 5s';
        $lines[] = '      retries: 3';

        return implode("\n", $lines) . "\n";
    }

    private function databaseService(): string
    {
        if ($this->config->database === 'mysql') {
            return $this->mysqlService();
        }

        return $this->postgresService();
    }

    private function postgresService(): string
    {
        $lines = [
            '  postgres:',
            sprintf('    image: %s', self::POSTGRES_IMAGE),
            '    ports:',
            sprintf('      - "%d:5432"', $this->config->dbPort),
            '    environment:',
            '      POSTGRES_DB: pulsar',
            '      POSTGRES_USER: pulsar',
            '      POSTGRES_PASSWORD: secret',
            '    volumes:',
            '      - db-data:/var/lib/postgresql/data',
            '    healthcheck:',
            '      test: ["CMD-SHELL", "pg_isready -U pulsar"]',
            '      interval: 5s',
            '      timeout: 5s',
            '      retries: 5',
        ];

        return implode("\n", $lines) . "\n";
    }

    private function mysqlService(): string
    {
        $lines = [
            '  mysql:',
            sprintf('    image: %s', self::MYSQL_IMAGE),
            '    ports:',
            sprintf('      - "%d:3306"', $this->config->dbPort),
            '    environment:',
            '      MYSQL_DATABASE: pulsar',
            '      MYSQL_USER: pulsar',
            '      MYSQL_PASSWORD: secret',
            '      MYSQL_ROOT_PASSWORD: secret',
            '    volumes:',
            '      - db-data:/var/lib/mysql',
            '    healthcheck:',
            '      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]',
            '      interval: 5s',
            '      timeout: 5s',
            '      retries: 5',
        ];

        return implode("\n", $lines) . "\n";
    }

    private function redisService(): string
    {
        $lines = [
            '  redis:',
            sprintf('    image: %s', self::REDIS_IMAGE),
            '    ports:',
            sprintf('      - "%d:6379"', $this->config->redisPort),
            '    volumes:',
            '      - redis-data:/data',
            '    healthcheck:',
            '      test: ["CMD", "redis-cli", "ping"]',
            '      interval: 5s',
            '      timeout: 5s',
            '      retries: 5',
        ];

        return implode("\n", $lines) . "\n";
    }

    private function mailpitService(): string
    {
        $lines = [
            '  mailpit:',
            sprintf('    image: %s', self::MAILPIT_IMAGE),
            '    ports:',
            sprintf('      - "%d:1025"', $this->config->mailpitSmtpPort),
            sprintf('      - "%d:8025"', $this->config->mailpitWebPort),
        ];

        return implode("\n", $lines) . "\n";
    }

    private function databaseVolume(): string
    {
        return '  db-data:';
    }
}
