-------------------------- MODULE crypto --------------------------
(***************************************************************************)
(* Pulsar Framework — Sprint 1.1 / Phase 1.1.D.1.                          *)
(*                                                                         *)
(* TLA+ specification of cryptographic key lifecycle in                    *)
(* `pulsar-kernel::crypto`. Models the abstract state machine that every   *)
(* secret-bearing key handle traverses, regardless of underlying primitive *)
(* (AEAD / HMAC / Ed25519 / X25519 / ML-KEM-768 / ML-DSA-65 / hybrids).    *)
(*                                                                         *)
(* The cryptographic operations themselves (encrypt, sign, verify, KEM    *)
(* encapsulate, derive, etc.) are out of scope: their correctness is      *)
(* anchored in HACL* (classical primitives, Decision 2.53) and libcrux    *)
(* (PQC primitives, Decision 2.60) via formal F* / hax verification at    *)
(* the primitive-arithmetic level. This spec covers what HACL* and        *)
(* libcrux do NOT — the ENGINEERING-LEVEL state machine that wraps every  *)
(* primitive and binds it to a lifecycle (generation, use, rotation,      *)
(* secure erase) that must hold under any concurrent interleaving across  *)
(* threads, requests, and key contexts.                                   *)
(*                                                                         *)
(* See: docs/plan.md Section II Decision 2.20 (formal verification:       *)
(* Creusot for function contracts, TLA+ for protocol specifications);     *)
(* Decision 2.53 (HACL* via FFI for classical primitives); Decision 2.60  *)
(* (libcrux for PQC primitives); Section XII success metrics (15 TLA+    *)
(* specifications at GA per Decision 2.59 v2.3 lock-in); spec/README.md   *)
(* for the spec catalogue.                                                *)
(*                                                                         *)
(* ## States                                                               *)
(*                                                                         *)
(* Every key slot occupies exactly one of:                                *)
(*   - Zeroised : terminal-or-unallocated. The slot holds no live key    *)
(*     material; any prior material has been wiped via the secrecy +     *)
(*     zeroize layered guarantees from Phase 1.1.B.3 / 1.1.C.2. The      *)
(*     INITIAL state of every slot.                                       *)
(*   - Fresh    : just generated by CSPRNG (Phase 1.1.B.5 abstraction);  *)
(*     not yet used in any cryptographic operation.                      *)
(*   - InUse    : has been used at least once. Idempotent — a key may    *)
(*     be used arbitrarily many times while remaining InUse.             *)
(*   - Rotating : a successor key has been minted to replace this one;   *)
(*     this key is on its way out. It still services existing            *)
(*     verification or decapsulation requests until the rotation         *)
(*     completes via CompleteRotation, at which point this slot is       *)
(*     Zeroised.                                                          *)
(*                                                                         *)
(* ## Transitions                                                          *)
(*                                                                         *)
(*   Zeroised --Generate------> Fresh                                     *)
(*   Fresh    --Use-----------> InUse                                     *)
(*   InUse    --Use-----------> InUse                       (idempotent) *)
(*   InUse    --BeginRotation-> Rotating  (successor s ∈ {Fresh, InUse}) *)
(*   Rotating --CompleteRot---> Zeroised  (successor still live)         *)
(*   *        --EmergencyZero-> Zeroised  (any non-Zeroised; cascades to *)
(*                                         keys rotating-to this one)    *)
(*                                                                         *)
(* ## Bounded model check                                                  *)
(*                                                                         *)
(* Model parameters (`crypto.cfg`):                                       *)
(*   - MaxKeys = 4 (slot count). Enough to exhibit two concurrent        *)
(*     rotations (4 = 2 rotators + 2 successors). Above that the state   *)
(*     space grows quadratically without surfacing additional behaviours.*)
(*                                                                         *)
(* TLC verifies:                                                          *)
(*   - INVARIANT KeyLifecycleSafety  (conjunction of 6 safety invariants)*)
(*   - PROPERTY  RotatingEventuallyZeroised   (liveness under fairness)  *)
(*                                                                         *)
(* No nested rotations (a Rotating key may not itself be the successor   *)
(* of a third key) — this restriction keeps the model bounded and        *)
(* mirrors the Pulsar engineering convention that quarterly key rotation *)
(* is sequential per-domain (master / TLS / API token / etc.).           *)
(***************************************************************************)
EXTENDS Naturals

CONSTANT MaxKeys

ASSUME MaxKeysBounded == MaxKeys \in Nat /\ MaxKeys >= 1

(* The bounded set of key SLOTS in the model. Each slot represents a    *)
(* memory cell that may hold zero or one live key over time — slots are *)
(* recycled after Zeroise via Generate. The slot identity (KeyId) is    *)
(* distinct from the key material identity, which is implicit.          *)
KeyIds == 1..MaxKeys

(* The lifecycle states a slot can occupy.                              *)
States == {"Zeroised", "Fresh", "InUse", "Rotating"}

(* Sentinel value for `successor` map entries that point to no slot     *)
(* (i.e. the key is not currently rotating).                            *)
NoSuccessor == 0

(***************************************************************************)
(* Variables.                                                              *)
(*                                                                         *)
(* keyState[k]  : current lifecycle state of slot k                       *)
(* successor[k] : during rotation, the slot ID of the replacement key;    *)
(*                NoSuccessor (= 0) when k is not Rotating.              *)
(***************************************************************************)
VARIABLE keyState, successor

vars == <<keyState, successor>>

TypeOK ==
    /\ keyState \in [KeyIds -> States]
    /\ successor \in [KeyIds -> {NoSuccessor} \cup KeyIds]

(***************************************************************************)
(* Initial state: every slot starts Zeroised (unallocated).              *)
(***************************************************************************)
Init ==
    /\ keyState = [k \in KeyIds |-> "Zeroised"]
    /\ successor = [k \in KeyIds |-> NoSuccessor]

(***************************************************************************)
(* Action: Generate                                                       *)
(*                                                                         *)
(* Allocate a new key in slot k via the OS CSPRNG.                       *)
(*                                                                         *)
(* Precondition : slot is currently Zeroised (unallocated).              *)
(* Effect       : Zeroised → Fresh.                                      *)
(***************************************************************************)
Generate(k) ==
    /\ keyState[k] = "Zeroised"
    /\ keyState' = [keyState EXCEPT ![k] = "Fresh"]
    /\ UNCHANGED successor

(***************************************************************************)
(* Action: Use                                                            *)
(*                                                                         *)
(* Use the key in slot k for any cryptographic operation (sign, encrypt, *)
(* derive, encapsulate, ...). Idempotent — repeated use stays InUse.     *)
(*                                                                         *)
(* Precondition : keyState[k] ∈ {Fresh, InUse}.                          *)
(* Effect       : Fresh → InUse  OR  InUse → InUse.                      *)
(***************************************************************************)
Use(k) ==
    /\ keyState[k] \in {"Fresh", "InUse"}
    /\ keyState' = [keyState EXCEPT ![k] = "InUse"]
    /\ UNCHANGED successor

(***************************************************************************)
(* Action: BeginRotation                                                  *)
(*                                                                         *)
(* Begin rotation of slot k by minting a successor in slot s. The        *)
(* successor must already exist (in {Fresh, InUse}) — rotation does NOT *)
(* generate the replacement; the operator generates it independently and *)
(* then calls BeginRotation to bind it as the successor.                *)
(*                                                                         *)
(* Precondition :                                                         *)
(*   - k is in InUse (you can only rotate a key that's been used)        *)
(*   - s is in {Fresh, InUse} (NOT Rotating — no nested rotations)       *)
(*   - k # s (a key cannot be its own successor)                         *)
(*   - k is not already rotating (successor[k] = NoSuccessor)            *)
(*   - s is not the successor of any other slot (uniqueness)             *)
(*   - k is not the successor of any other slot (no nested rotations)    *)
(*                                                                         *)
(* Effect       : keyState[k] InUse → Rotating; successor[k] := s.       *)
(***************************************************************************)
BeginRotation(k, s) ==
    /\ k # s
    /\ keyState[k] = "InUse"
    /\ keyState[s] \in {"Fresh", "InUse"}
    /\ successor[k] = NoSuccessor
    /\ \A other \in KeyIds : successor[other] # s
    /\ \A other \in KeyIds : successor[other] # k
    /\ keyState' = [keyState EXCEPT ![k] = "Rotating"]
    /\ successor' = [successor EXCEPT ![k] = s]

(***************************************************************************)
(* Action: CompleteRotation                                               *)
(*                                                                         *)
(* Complete rotation of slot k — the replacement is fully promoted, and  *)
(* k's material is securely erased.                                      *)
(*                                                                         *)
(* Precondition :                                                         *)
(*   - k is Rotating                                                      *)
(*   - successor[k] is still in {Fresh, InUse} (i.e. the replacement is *)
(*     live and ready to take over)                                      *)
(*                                                                         *)
(* Effect       : Rotating → Zeroised; successor[k] cleared.             *)
(***************************************************************************)
CompleteRotation(k) ==
    /\ keyState[k] = "Rotating"
    /\ keyState[successor[k]] \in {"Fresh", "InUse"}
    /\ keyState' = [keyState EXCEPT ![k] = "Zeroised"]
    /\ successor' = [successor EXCEPT ![k] = NoSuccessor]

(***************************************************************************)
(* Action: EmergencyZeroise                                               *)
(*                                                                         *)
(* Emergency erase of slot k — used in compromise scenarios where the    *)
(* key material must be wiped immediately, regardless of rotation state. *)
(*                                                                         *)
(* If any slot is rotating-TO k (i.e. has k as its successor), the      *)
(* erase CASCADES to those slots — they would otherwise be left with a  *)
(* dangling successor pointer, violating RotatingHasLiveSuccessor.      *)
(*                                                                         *)
(* Precondition : keyState[k] # Zeroised.                                *)
(* Effect       : k → Zeroised; any slot with successor = k → Zeroised; *)
(*                all affected slots have successor cleared.            *)
(***************************************************************************)
EmergencyZeroise(k) ==
    /\ keyState[k] # "Zeroised"
    /\ keyState' = [other \in KeyIds |->
                       IF other = k \/ successor[other] = k
                       THEN "Zeroised"
                       ELSE keyState[other]]
    /\ successor' = [other \in KeyIds |->
                       IF other = k \/ successor[other] = k
                       THEN NoSuccessor
                       ELSE successor[other]]

(***************************************************************************)
(* Next-state relation: any one of the actions can fire on any one of   *)
(* the slots (or pair of slots, for BeginRotation).                      *)
(***************************************************************************)
Next ==
    \/ \E k \in KeyIds : Generate(k)
    \/ \E k \in KeyIds : Use(k)
    \/ \E k, s \in KeyIds : BeginRotation(k, s)
    \/ \E k \in KeyIds : CompleteRotation(k)
    \/ \E k \in KeyIds : EmergencyZeroise(k)

(***************************************************************************)
(* Fairness assumptions for liveness: every Rotating key eventually       *)
(* leaves the Rotating state. Without weak-fairness on either            *)
(* CompleteRotation or EmergencyZeroise, an adversarial scheduler could  *)
(* keep a key in Rotating indefinitely.                                  *)
(***************************************************************************)
Liveness ==
    /\ \A k \in KeyIds : WF_vars(CompleteRotation(k))
    /\ \A k \in KeyIds : WF_vars(EmergencyZeroise(k))

Spec == Init /\ [][Next]_vars /\ Liveness

(***************************************************************************)
(*                                                                         *)
(*                   I N V A R I A N T S   (safety)                       *)
(*                                                                         *)
(* Each invariant must hold at every reachable state of the model.       *)
(***************************************************************************)

(* Inv1: Type-correctness — slots and successor entries take values in   *)
(* their declared domains.                                               *)
\* (TypeOK is declared above)

(* Inv2: A Zeroised slot has no successor. Successor metadata is        *)
(* meaningful only during active rotation, and the act of zeroising     *)
(* clears it.                                                            *)
ZeroisedHasNoSuccessor ==
    \A k \in KeyIds : keyState[k] = "Zeroised" => successor[k] = NoSuccessor

(* Inv3: A non-Rotating slot has no successor. Successor is rotation-   *)
(* specific bookkeeping; it should never be set when the slot is not    *)
(* Rotating.                                                             *)
NonRotatingHasNoSuccessor ==
    \A k \in KeyIds : keyState[k] # "Rotating" => successor[k] = NoSuccessor

(* Inv4: A Rotating slot has a LIVE successor — i.e. successor[k] is a  *)
(* valid slot ID, and that slot is in {Fresh, InUse}. This is the       *)
(* safety-critical invariant: if a Rotating slot's successor were dead, *)
(* the rotation would leave a window with no key servicing operations.  *)
(*                                                                         *)
(* No nested rotations (the successor is NOT itself Rotating) — this    *)
(* restriction keeps the model bounded and reflects engineering reality *)
(* that quarterly rotation is sequential per-domain.                    *)
RotatingHasLiveSuccessor ==
    \A k \in KeyIds :
        keyState[k] = "Rotating" =>
            /\ successor[k] \in KeyIds
            /\ keyState[successor[k]] \in {"Fresh", "InUse"}

(* Inv5: A slot is never its own successor.                             *)
NoSelfSuccessor ==
    \A k \in KeyIds : successor[k] # k

(* Inv6: Each slot is the successor of at most one Rotating slot. This  *)
(* prevents the "two parents" pathology where two distinct Rotating     *)
(* keys both believe they're being replaced by the same successor.     *)
SuccessorIsUnique ==
    \A k1, k2 \in KeyIds :
        ( /\ k1 # k2
          /\ successor[k1] # NoSuccessor
          /\ successor[k2] # NoSuccessor )
        => successor[k1] # successor[k2]

(* Conjunction of all safety invariants — declared in `crypto.cfg` as    *)
(* the single INVARIANT to check.                                        *)
KeyLifecycleSafety ==
    /\ TypeOK
    /\ ZeroisedHasNoSuccessor
    /\ NonRotatingHasNoSuccessor
    /\ RotatingHasLiveSuccessor
    /\ NoSelfSuccessor
    /\ SuccessorIsUnique

(***************************************************************************)
(*                                                                         *)
(*                P R O P E R T I E S   (liveness)                        *)
(*                                                                         *)
(* Temporal properties checked under the fairness assumptions in Spec.  *)
(***************************************************************************)

(* Prop1: Any slot in Rotating state eventually transitions to Zeroised. *)
(* Under WF_vars on CompleteRotation + EmergencyZeroise, no slot can be *)
(* indefinitely stuck in Rotating — it must either complete its         *)
(* rotation (CompleteRotation) or be emergency-erased (EmergencyZeroise).*)
RotatingEventuallyZeroised ==
    \A k \in KeyIds : (keyState[k] = "Rotating") ~> (keyState[k] = "Zeroised")

================================================================================
\* Modification history
\* Created by Pulsar Framework Sprint 1.1.D.1 — 2026-04-29.
