[package]
name = "pulsar-orm"
description = "Typed ORM on sqlx with nineteen derive attributes including event sourcing and RLS."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-kernel = { path = "../pulsar-kernel", version = "=0.0.1-alpha.0" }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
darling = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }

[lints]
workspace = true
