[package]
name = "pulsar-cms"
description = "First-party content management system with workflows, taxonomies, media."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-engine = { path = "../pulsar-engine", version = "=0.0.1-alpha.0" }
pulsar-orchestration = { path = "../pulsar-orchestration", version = "=0.0.1-alpha.0" }
pulsar-feature-flag = { path = "../pulsar-feature-flag", version = "=0.0.1-alpha.0" }
pulsar-search = { path = "../pulsar-search", version = "=0.0.1-alpha.0" }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
