<?php

declare(strict_types=1);

namespace Pulsar\Container\Compiled;

use Pulsar\Api\Internal;
use Pulsar\Container\Exception\ContainerException;
use Pulsar\Container\ServiceDefinition;
use ReflectionClass;
use ReflectionNamedType;

use function class_exists;
use function implode;
use function is_string;
use function ksort;
use function preg_match;
use function preg_replace;
use function sprintf;
use function str_replace;
use function var_export;

use const SORT_STRING;

/**
 * Generates optimized PHP code from service definitions.
 *
 * Produces a PHP class extending CompiledContainer with a factory method
 * for each service. Pre-resolves dependency chains for flat array lookups
 * with no runtime reflection.
 */
#[Internal]
final class ContainerCompiler
{
    /**
     * Compile service definitions into a PHP class string.
     *
     * @param array<string, ServiceDefinition> $definitions
     * @param string $className Generated class name (default: CompiledContainerGenerated)
     * @param string $namespace Generated namespace
     * @return string PHP source code
     */
    public static function compile(
        array $definitions,
        string $className = 'CompiledContainerGenerated',
        string $namespace = 'Pulsar\\Container\\Compiled',
    ): string {
        ksort($definitions, SORT_STRING);

        $methodMap = [];
        $lifetimeMap = [];
        $depsMap = [];
        $methods = [];

        foreach ($definitions as $id => $definition) {
            $methodName = self::serviceIdToMethodName($id);
            $methodMap[$id] = $methodName;
            $lifetimeMap[$id] = $definition->lifetime->value;

            $concrete = $definition->concrete;

            if (is_string($concrete)) {
                $depsMap[$id] = self::resolveDependencyIds($concrete, $definitions);
                $methods[] = self::generateClassFactoryMethod($methodName, $id, $concrete, $definition);
            } else {
                // Callable factories cannot be compiled — generate a placeholder
                // that throws at runtime. The optimize command should warn about these.
                $methods[] = self::generateUnsupportedFactoryMethod($methodName, $id);
            }
        }

        $methodMapCode = self::generateMethodMapCode($methodMap);
        $lifetimeMapCode = self::generateLifetimeMapCode($lifetimeMap);
        $depsCode = self::generateDepsCode($depsMap);
        $methodsCode = implode("\n\n", $methods);

        return <<<PHP
            <?php

            declare(strict_types=1);

            namespace {$namespace};

            use Pulsar\Container\Lifetime;

            /**
             * Auto-generated compiled container. DO NOT EDIT.
             *
             * Generated by Pulsar ContainerCompiler.
             */
            final class {$className} extends CompiledContainer
            {
            {$methodMapCode}

            {$lifetimeMapCode}

            {$depsCode}

            {$methodsCode}
            }

            PHP;
    }

    /**
     * Convert a service ID (FQCN) to a valid PHP method name.
     */
    private static function serviceIdToMethodName(string $id): string
    {
        $sanitized = str_replace('\\', '_', $id);
        $sanitized = (string) preg_replace('/[^a-zA-Z0-9_]/', '_', $sanitized);

        return 'create_' . $sanitized;
    }

    /**
     * Generate a factory method for a class-based service.
     *
     * @param class-string $concrete
     *
     * @throws ContainerException If the concrete class name is not a valid FQCN
     */
    private static function generateClassFactoryMethod(
        string $methodName,
        string $id,
        string $concrete,
        ServiceDefinition $definition,
    ): string {
        // S5: Validate FQCN to prevent code injection via interpolation
        if (preg_match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff\\\\]*$/', $concrete) !== 1) {
            throw new ContainerException(sprintf(
                'Invalid class name "%s" for service "%s". Class names must be valid PHP FQCNs.',
                $concrete,
                $id,
            ));
        }

        $escapedId = var_export($id, true);
        $escapedConcrete = '\\' . ltrim($concrete, '\\');

        return <<<PHP
                /**
                 * Service: {$id}
                 * Lifetime: {$definition->lifetime->value}
                 */
                private function {$methodName}(): object
                {
                    return new {$escapedConcrete}(
                        ...array_map(fn(string \$dep) => \$this->get(\$dep), self::DEPS[{$escapedId}] ?? [])
                    );
                }
            PHP;
    }

    /**
     * Generate a stub for callable factories that can't be compiled.
     */
    private static function generateUnsupportedFactoryMethod(string $methodName, string $id): string
    {
        $escapedId = var_export($id, true);

        return <<<PHP
                /**
                 * Service: {$id} (callable factory — not compilable)
                 */
                private function {$methodName}(): object
                {
                    throw new \Pulsar\Container\Exception\ContainerException(
                        'Service ' . {$escapedId} . ' uses a callable factory and cannot be compiled. '
                        . 'Use a class-string binding for compilation support.'
                    );
                }
            PHP;
    }

    /**
     * Generate the $methodMap property initialization.
     *
     * @param array<string, string> $methodMap
     */
    private static function generateMethodMapCode(array $methodMap): string
    {
        $entries = [];
        foreach ($methodMap as $id => $method) {
            $entries[] = sprintf("        %s => '%s',", var_export($id, true), $method);
        }

        $entriesCode = implode("\n", $entries);

        return <<<PHP
                protected array \$methodMap = [
            {$entriesCode}
                ];
            PHP;
    }

    /**
     * Generate the $lifetimeMap property mapping service IDs to lifetime values.
     *
     * @param array<string, string> $lifetimeMap Service ID → Lifetime enum value
     */
    private static function generateLifetimeMapCode(array $lifetimeMap): string
    {
        $entries = [];
        foreach ($lifetimeMap as $id => $lifetime) {
            $entries[] = sprintf(
                '        %s => Lifetime::%s,',
                var_export($id, true),
                match ($lifetime) {
                    'singleton' => 'Singleton',
                    'transient' => 'Transient',
                    'request' => 'RequestScope',
                    'tenant' => 'TenantScope',
                    default => 'Singleton',
                },
            );
        }

        $entriesCode = implode("\n", $entries);

        return <<<PHP
                protected array \$lifetimeMap = [
            {$entriesCode}
                ];
            PHP;
    }

    /**
     * Generate the DEPS constant mapping service IDs to their constructor dependency IDs.
     *
     * @param array<string, list<string>> $depsMap Service ID → list of dependency service IDs
     */
    private static function generateDepsCode(array $depsMap): string
    {
        $entries = [];
        foreach ($depsMap as $id => $deps) {
            if ($deps === []) {
                $entries[] = sprintf('        %s => [],', var_export($id, true));
            } else {
                $depsList = implode(', ', array_map(
                    static fn(string $dep): string => var_export($dep, true),
                    $deps,
                ));
                $entries[] = sprintf('        %s => [%s],', var_export($id, true), $depsList);
            }
        }

        $entriesCode = implode("\n", $entries);

        return <<<PHP
                private const array DEPS = [
            {$entriesCode}
                ];
            PHP;
    }

    /**
     * Resolve constructor dependency service IDs for a concrete class.
     *
     * Uses reflection to inspect constructor parameters and map them back
     * to service IDs from the definitions map.
     *
     * @param class-string $concrete
     * @param array<string, ServiceDefinition> $definitions
     * @return list<string>
     */
    private static function resolveDependencyIds(string $concrete, array $definitions): array
    {
        if (!class_exists($concrete)) {
            return [];
        }

        $reflector = new ReflectionClass($concrete);
        $constructor = $reflector->getConstructor();

        if ($constructor === null) {
            return [];
        }

        $deps = [];
        foreach ($constructor->getParameters() as $param) {
            $type = $param->getType();

            if (!$type instanceof ReflectionNamedType || $type->isBuiltin()) {
                continue;
            }

            $typeName = $type->getName();

            // Map to a service ID: check definitions first, then use the type name directly
            if (isset($definitions[$typeName])) {
                $deps[] = $typeName;
            }
        }

        return $deps;
    }
}
