<?php

declare(strict_types=1);

namespace Pulsar\I18n\Compiler;

use DirectoryIterator;
use Pulsar\Api\Internal;

use function array_keys;
use function file_get_contents;
use function hash;
use function hash_file;
use function implode;
use function is_array;
use function is_dir;
use function is_file;
use function is_string;
use function json_decode;
use function ksort;
use function pathinfo;
use function sort;
use function str_replace;
use function var_export;

use const DIRECTORY_SEPARATOR;
use const JSON_THROW_ON_ERROR;
use const SORT_STRING;

/**
 * Build-time compiler: generates a compiled i18n catalog index.
 *
 * Scans all catalog sources (JSON/PHP) across locales and domains,
 * producing a unified index for production use without runtime scanning.
 */
#[Internal]
final class I18nCatalogCompiler
{
    /**
     * Compile catalog sources into a catalog index.
     *
     * Scans the catalog path for locale directories containing
     * domain files (JSON or PHP), producing a deterministic index.
     *
     * @param string $catalogPath Root catalog directory (e.g., `resources/lang`)
     * @return CompiledCatalogIndex
     */
    public function compile(string $catalogPath): CompiledCatalogIndex
    {
        $locales = $this->discoverLocales($catalogPath);
        sort($locales, SORT_STRING);

        $index = [];
        $fileHashes = [];

        foreach ($locales as $locale) {
            $localePath = $catalogPath . DIRECTORY_SEPARATOR . $locale;
            $domains = $this->discoverDomains($localePath);
            sort($domains, SORT_STRING);

            $index[$locale] = [];

            foreach ($domains as $domain) {
                $keys = $this->extractKeys($localePath, $domain);
                sort($keys, SORT_STRING);

                $index[$locale][$domain] = $keys;

                // Compute file hashes for staleness detection
                $filePath = $this->resolveDomainFile($localePath, $domain);

                if ($filePath !== null) {
                    $relativePath = str_replace('\\', '/', $locale . '/' . pathinfo($filePath, PATHINFO_BASENAME));
                    $fileHash = hash_file('sha256', $filePath);

                    if ($fileHash !== false) {
                        $fileHashes[$relativePath] = $fileHash;
                    }
                }
            }

            ksort($index[$locale], SORT_STRING);
        }

        ksort($index, SORT_STRING);
        ksort($fileHashes, SORT_STRING);

        // Compute total hash from all file hashes
        $hashParts = [];

        foreach ($fileHashes as $path => $fileHash) {
            $hashParts[] = $path . ':' . $fileHash;
        }

        $totalHash = hash('sha256', implode("\n", $hashParts));

        return new CompiledCatalogIndex(
            locales: array_keys($index),
            index: $index,
            fileHashes: $fileHashes,
            totalHash: $totalHash,
        );
    }

    /**
     * Export a compiled catalog index as PHP code returning the array.
     */
    public function export(CompiledCatalogIndex $catalogIndex): string
    {
        $exported = var_export($catalogIndex->toArray(), true);

        return "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by Pulsar I18nCatalogCompiler. Do not edit.\nreturn " . $exported . ";\n";
    }

    /**
     * Discover locale directories within the catalog path.
     *
     * @return list<string> Locale directory names
     */
    private function discoverLocales(string $catalogPath): array
    {
        if (!is_dir($catalogPath)) {
            return [];
        }

        $locales = [];
        $iterator = new DirectoryIterator($catalogPath);

        foreach ($iterator as $item) {
            if ($item->isDot() || !$item->isDir()) {
                continue;
            }

            $locales[] = $item->getFilename();
        }

        return $locales;
    }

    /**
     * Discover translation domain files within a locale directory.
     *
     * @return list<string> Domain names (without extension)
     */
    private function discoverDomains(string $localePath): array
    {
        if (!is_dir($localePath)) {
            return [];
        }

        $domains = [];
        $seen = [];
        $iterator = new DirectoryIterator($localePath);

        foreach ($iterator as $item) {
            if ($item->isDot() || !$item->isFile()) {
                continue;
            }

            $ext = $item->getExtension();

            if ($ext !== 'json' && $ext !== 'php') {
                continue;
            }

            $domain = pathinfo($item->getFilename(), PATHINFO_FILENAME);

            if (!isset($seen[$domain])) {
                $domains[] = $domain;
                $seen[$domain] = true;
            }
        }

        return $domains;
    }

    /**
     * Extract translation keys from a domain file.
     *
     * @return list<string>
     */
    private function extractKeys(string $localePath, string $domain): array
    {
        // Try JSON first, then PHP
        $jsonPath = $localePath . DIRECTORY_SEPARATOR . $domain . '.json';

        if (is_file($jsonPath)) {
            return $this->extractKeysFromJson($jsonPath);
        }

        $phpPath = $localePath . DIRECTORY_SEPARATOR . $domain . '.php';

        if (is_file($phpPath)) {
            return $this->extractKeysFromPhp($phpPath);
        }

        return [];
    }

    /**
     * Resolve the physical file path for a domain.
     */
    private function resolveDomainFile(string $localePath, string $domain): ?string
    {
        $jsonPath = $localePath . DIRECTORY_SEPARATOR . $domain . '.json';

        if (is_file($jsonPath)) {
            return $jsonPath;
        }

        $phpPath = $localePath . DIRECTORY_SEPARATOR . $domain . '.php';

        if (is_file($phpPath)) {
            return $phpPath;
        }

        return null;
    }

    /**
     * @return list<string>
     */
    private function extractKeysFromJson(string $path): array
    {
        $contents = file_get_contents($path);

        if ($contents === false) {
            return [];
        }

        /** @var array<string, mixed>|null $data */
        $data = json_decode($contents, true, flags: JSON_THROW_ON_ERROR);

        if ($data === null) {
            return [];
        }

        $keys = [];

        foreach (array_keys($data) as $key) {
            if (is_string($key)) {
                $keys[] = $key;
            }
        }

        return $keys;
    }

    /**
     * @return list<string>
     */
    private function extractKeysFromPhp(string $path): array
    {
        $data = require $path;

        if (!is_array($data)) {
            return [];
        }

        $keys = [];

        foreach (array_keys($data) as $key) {
            if (is_string($key)) {
                $keys[] = $key;
            }
        }

        return $keys;
    }
}
