<?php

declare(strict_types=1);

namespace Pulsar\Tests\Unit\Console\Command\NewProject;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Pulsar\Console\Command\NewProject\ComposerJsonGenerator;
use Pulsar\Console\Command\NewProject\ProjectPreset;
use Pulsar\Core\Version;

use function array_keys;
use function assert;
use function dirname;
use function file_get_contents;
use function implode;
use function is_array;
use function is_string;
use function json_decode;
use function ltrim;
use function version_compare;

#[CoversClass(ComposerJsonGenerator::class)]
final class ComposerJsonGeneratorTest extends TestCase
{
    #[Test]
    public function generateProducesValidJson(): void
    {
        $generator = new ComposerJsonGenerator();

        $json = $generator->generate('MyHealthApp', ProjectPreset::Web);
        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($decoded));

        self::assertArrayHasKey('name', $decoded);
        self::assertArrayHasKey('require', $decoded);
        self::assertSame('app/my-health-app', $decoded['name']);
        $require = $decoded['require'];
        assert(is_array($require));
        self::assertSame('>=8.5', $require['php']);
    }

    /**
     * The framework requirement must name the package this repository publishes.
     *
     * This is the assertion that was missing. The generator carried its own copy of
     * the package name, still spelling the pre-rename `lennyobez/pulsar`, and the
     * only test of it read that same copy back -- so it agreed with itself for as
     * long as it was wrong, and every project `pulsar init` produced required a
     * package that has never existed under that name. Comparing against the `name`
     * in this repository's own `composer.json` is the only comparison that can
     * fail, so it is the only one worth making.
     */
    #[Test]
    public function generateRequiresThePackageThisRepositoryPublishes(): void
    {
        $manifest = file_get_contents(dirname(__DIR__, 5) . '/composer.json');
        self::assertIsString($manifest, 'The repository composer.json could not be read.');

        $root = json_decode($manifest, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($root));
        $packageName = $root['name'];
        assert(is_string($packageName));

        $json = new ComposerJsonGenerator()->generate('MyHealthApp', ProjectPreset::Web);
        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($decoded));
        $require = $decoded['require'];
        assert(is_array($require));

        self::assertArrayHasKey(
            $packageName,
            $require,
            'A scaffolded project requires ' . implode(', ', array_keys($require)) . ', which does not '
            . 'include ' . $packageName . ' -- the package this repository is. `composer install` inside '
            . 'a project generated by `pulsar init` resolves nothing, and the project cannot be built.',
        );
    }

    /**
     * The constraint has to admit the framework that wrote it.
     *
     * `^1.0` was emitted throughout the release-candidate phase, and Composer orders
     * `1.0.0-rc.12` BELOW `1.0.0`, so the constraint excluded every Pulsar that
     * existed when it was written. Deriving it from the framework's own version is
     * what keeps the two in step; comparing the emitted constraint against
     * `Version::full()` is what proves the derivation still holds.
     */
    #[Test]
    public function generateEmitsAConstraintTheRunningFrameworkSatisfies(): void
    {
        $json = new ComposerJsonGenerator()->generate('MyHealthApp', ProjectPreset::Web);
        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($decoded));
        $require = $decoded['require'];
        assert(is_array($require));
        $constraint = $require[ComposerJsonGenerator::FRAMEWORK_PACKAGE];
        assert(is_string($constraint));

        self::assertSame('^' . Version::full(), $constraint);

        // The property that matters, stated the way Composer reads it: the caret's
        // lower bound is the framework doing the scaffolding, so a project generated
        // by this build can resolve this build.
        self::assertTrue(
            version_compare(Version::full(), ltrim($constraint, '^'), '>='),
            'A project scaffolded by Pulsar ' . Version::full() . ' declares ' . $constraint
            . ', which that same Pulsar does not satisfy.',
        );
    }

    #[Test]
    public function generateIncludesPresetInDescription(): void
    {
        $generator = new ComposerJsonGenerator();

        $json = $generator->generate('BankingApi', ProjectPreset::Api);
        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($decoded));

        $description = $decoded['description'];
        assert(is_string($description));
        self::assertStringContainsString('api', $description);
    }

    #[Test]
    public function generateSlugifiesAppName(): void
    {
        $generator = new ComposerJsonGenerator();

        $json = $generator->generate('My Complex_App Name', ProjectPreset::Minimal);
        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($decoded));

        self::assertSame('app/my-complex-app-name', $decoded['name']);
    }

    #[Test]
    public function generateSetsAutoloadPaths(): void
    {
        $generator = new ComposerJsonGenerator();

        $json = $generator->generate('TestApp', ProjectPreset::Web);
        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        assert(is_array($decoded));
        $autoload = $decoded['autoload'];
        assert(is_array($autoload));
        $autoloadDev = $decoded['autoload-dev'];
        assert(is_array($autoloadDev));

        self::assertSame(['App\\' => 'src/'], $autoload['psr-4']);
        self::assertSame(['Tests\\' => 'tests/'], $autoloadDev['psr-4']);
    }

    #[Test]
    public function generateEndsWithNewline(): void
    {
        $generator = new ComposerJsonGenerator();

        $json = $generator->generate('App', ProjectPreset::Minimal);

        self::assertStringEndsWith("\n", $json);
    }
}
