[package]
name = "pulsar-form"
description = "Typed form builder with validation, MIME sniffer, CSRF integration."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-guard = { path = "../pulsar-guard", version = "=0.0.1-alpha.0" }
serde = { workspace = true }
validator = { workspace = true }
infer = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
