[package]
name = "pulsar-mail"
description = "SMTP transport, MJML templates, webhook verifiers, bounce parsing, DMARC."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-framework = { path = "../pulsar-framework", version = "=0.0.1-alpha.0" }
lettre = { workspace = true }
rustls = { workspace = true }
mrml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
