<?php

declare(strict_types=1);

namespace Pulsar\Console\Command;

use Override;
use Pulsar\Api\Internal;
use Pulsar\Console\Command;
use Pulsar\Console\ExitCode;
use Pulsar\Console\InputInterface;
use Pulsar\Console\OutputInterface;
use Pulsar\Container\ContainerInterface;
use ReflectionClass;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;

use function count;
use function date;
use function file_put_contents;
use function getcwd;
use function implode;
use function sprintf;

/**
 * Generate an IDE helper file for autocompletion.
 *
 * Introspects the container bindings to produce a `_ide_helper.php`
 * file with type-hinted stubs for IDE autocompletion.
 *
 * Usage: ide:helper [--output=_ide_helper.php]
 */
#[Internal]
final class IdeHelperCommand extends Command
{
    public function __construct(
        private readonly ContainerInterface $container,
    ) {
        parent::__construct();
    }

    #[Override]
    protected function configure(): void
    {
        $this->name = 'ide:helper';
        $this->description = 'Generate IDE helper file for autocompletion';
        $this->addOption('output', 'Output file path', 'o', '_ide_helper.php');
    }

    #[Override]
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $outputFile = $input->getStringOption('output', '_ide_helper.php');

        $cwd = getcwd();

        if ($cwd === false) {
            $output->errorln('Failed to determine current working directory.');
            return ExitCode::Error->value;
        }

        $filePath = $cwd . DIRECTORY_SEPARATOR . $outputFile;

        $output->writeln('Generating IDE helper file...');

        $bindings = $this->container->getBindings();
        $content = $this->generateHelperContent($bindings);

        file_put_contents($filePath, $content);

        $output->success(sprintf('IDE helper generated: %s (%d bindings)', $filePath, count($bindings)));
        $output->writeln('Add this file to your .gitignore and IDE include path.');

        return ExitCode::Success->value;
    }

    /**
     * @param list<string> $bindings
     */
    private function generateHelperContent(array $bindings): string
    {
        $date = date('Y-m-d H:i:s');

        $sections = [
            "<?php\n",
            "/**\n",
            " * Pulsar IDE Helper File.\n",
            " *\n",
            " * Auto-generated by pulsar ide:helper on {$date}.\n",
            " * Do not edit manually. Regenerate with: pulsar ide:helper\n",
            " *\n",
            " * @noinspection ALL\n",
            " */\n",
            "\n",
        ];

        $stubs = [];

        foreach ($bindings as $id) {
            if (!class_exists($id) && !interface_exists($id)) {
                continue;
            }

            $reflection = new ReflectionClass($id);

            if ($reflection->isInterface()) {
                $stubs[] = $this->generateInterfaceStub($reflection);
            }
        }

        if ($stubs !== []) {
            $sections[] = implode("\n", $stubs);
        }

        // Add container accessor type hints
        $sections[] = "\n/**\n";
        $sections[] = " * Container type map for IDE autocompletion.\n";
        $sections[] = " *\n";

        foreach ($bindings as $id) {
            if (class_exists($id) || interface_exists($id)) {
                $sections[] = sprintf(" * @method \\%s get(string \$id) @see \\Pulsar\\Container\\ContainerInterface::get()\n", $id);
            }
        }

        $sections[] = " */\n";
        $sections[] = "interface PulsarContainerTypeMap {}\n";

        return implode('', $sections);
    }

    /**
     * @param ReflectionClass<object> $reflection
     */
    private function generateInterfaceStub(ReflectionClass $reflection): string
    {
        $methods = [];

        foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
            if ($method->isConstructor() || $method->isDestructor()) {
                continue;
            }

            $params = [];

            foreach ($method->getParameters() as $param) {
                $params[] = $this->formatParameter($param);
            }

            $returnType = '';
            $rt = $method->getReturnType();

            if ($rt instanceof ReflectionNamedType) {
                $returnType = ': ' . ($rt->allowsNull() ? '?' : '') . $rt->getName();
            }

            $paramStr = implode(', ', $params);
            $methods[] = sprintf(
                "     * @method %s %s(%s)\n",
                $returnType !== '' ? ltrim($returnType, ': ') : 'mixed',
                $method->getName(),
                $paramStr,
            );
        }

        $stub = "/**\n";
        $stub .= sprintf(" * @see \\%s\n", $reflection->getName());

        if ($methods !== []) {
            $stub .= " *\n";
            $stub .= implode('', $methods);
        }

        $stub .= " */\n";

        return $stub;
    }

    private function formatParameter(ReflectionParameter $param): string
    {
        $type = $param->getType();
        $prefix = '';

        if ($type instanceof ReflectionNamedType) {
            $prefix = ($type->allowsNull() ? '?' : '') . $type->getName() . ' ';
        }

        $result = $prefix . '$' . $param->getName();

        if ($param->isDefaultValueAvailable()) {
            /** @var mixed $default */
            $default = $param->getDefaultValue();
            $result .= ' = ' . var_export($default, true);
        }

        return $result;
    }
}
