[package]
name = "pulsar-storage"
description = "Object storage abstraction over S3, Azure Blob, GCS, MinIO, local filesystem."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-kernel = { path = "../pulsar-kernel", version = "=0.0.1-alpha.0" }
object_store = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
