[package]
name = "pulsar-api"
description = "REST API framework with OpenAPI 3.1, AsyncAPI 3, optional OData v4."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-http = { path = "../pulsar-http", version = "=0.0.1-alpha.0" }
pulsar-pagination = { path = "../pulsar-pagination", version = "=0.0.1-alpha.0" }
utoipa = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
odata = []
