<?php

declare(strict_types=1);

namespace Pulsar\Tests\Unit\Deploy\Snippet;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Pulsar\Config\DeployConfig;
use Pulsar\Deploy\Snippet\ProxySnippetGenerator;

#[CoversClass(ProxySnippetGenerator::class)]
final class ProxySnippetGeneratorTest extends TestCase
{
    #[Test]
    public function it_generates_snippet_with_header(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringContainsString('# Reverse Proxy Configuration Snippet', $output);
        self::assertStringContainsString('Generated by Pulsar deploy:check', $output);
    }

    #[Test]
    public function it_includes_trusted_proxy_headers_section(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringContainsString('X-Forwarded-For', $output);
        self::assertStringContainsString('X-Forwarded-Proto', $output);
        self::assertStringContainsString('X-Forwarded-Host', $output);
        self::assertStringContainsString('X-Forwarded-Port', $output);
    }

    #[Test]
    public function it_lists_trusted_proxy_addresses_when_configured(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig(trustedProxies: ['10.0.0.0/8', '172.16.0.0/12']);

        $output = $generator->generate($config);

        self::assertStringContainsString('allow 10.0.0.0/8', $output);
        self::assertStringContainsString('allow 172.16.0.0/12', $output);
    }

    #[Test]
    public function it_shows_no_proxies_message_when_empty(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig(trustedProxies: []);

        $output = $generator->generate($config);

        self::assertStringContainsString('No trusted proxies configured', $output);
    }

    #[Test]
    public function it_includes_request_size_limits(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig(maxPostSizeMb: 32, maxUploadSizeMb: 64);

        $output = $generator->generate($config);

        self::assertStringContainsString('Maximum POST body size: 32MB', $output);
        self::assertStringContainsString('client_max_body_size 32m', $output);
        self::assertStringContainsString('Maximum upload size: 64MB', $output);
        self::assertStringContainsString('client_max_upload_size 64m', $output);
    }

    #[Test]
    public function it_includes_timeout_section(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringContainsString('proxy_connect_timeout', $output);
        self::assertStringContainsString('proxy_read_timeout', $output);
        self::assertStringContainsString('proxy_send_timeout', $output);
    }

    #[Test]
    public function it_includes_buffering_section(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringContainsString('proxy_buffering', $output);
        self::assertStringContainsString('proxy_buffer_size', $output);
    }

    #[Test]
    public function it_includes_health_check_section(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringContainsString('Health Check', $output);
        self::assertStringContainsString('/health', $output);
    }

    #[Test]
    public function it_ends_with_newline(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringEndsWith("\n", $output);
    }

    #[Test]
    public function it_includes_default_post_and_upload_sizes(): void
    {
        $generator = new ProxySnippetGenerator();
        $config = new DeployConfig();

        $output = $generator->generate($config);

        self::assertStringContainsString('Maximum POST body size: 8MB', $output);
        self::assertStringContainsString('Maximum upload size: 10MB', $output);
    }
}
