<?php

declare(strict_types=1);

namespace Pulsar\Tests\Unit\Deploy\Snippet;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Pulsar\Deploy\Snippet\TlsSnippetGenerator;

#[CoversClass(TlsSnippetGenerator::class)]
final class TlsSnippetGeneratorTest extends TestCase
{
    #[Test]
    public function it_generates_snippet_with_header(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('# TLS Configuration Snippet', $output);
        self::assertStringContainsString('Generated by Pulsar deploy:check', $output);
    }

    #[Test]
    public function it_includes_tls_protocol_versions(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('TLSv1.2', $output);
        self::assertStringContainsString('TLSv1.3', $output);
    }

    #[Test]
    public function it_includes_cipher_suites(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('TLS_AES_256_GCM_SHA384', $output);
        self::assertStringContainsString('TLS_CHACHA20_POLY1305_SHA256', $output);
        self::assertStringContainsString('TLS_AES_128_GCM_SHA256', $output);
        self::assertStringContainsString('ECDHE-ECDSA-AES256-GCM-SHA384', $output);
        self::assertStringContainsString('ECDHE-RSA-AES256-GCM-SHA384', $output);
    }

    #[Test]
    public function it_includes_hsts_section(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('HSTS', $output);
        self::assertStringContainsString('Strict-Transport-Security', $output);
        self::assertStringContainsString('max-age=31536000', $output);
    }

    #[Test]
    public function it_includes_ocsp_stapling(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('OCSP Stapling', $output);
        self::assertStringContainsString('ssl_stapling on', $output);
    }

    #[Test]
    public function it_includes_session_resumption(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('Session Resumption', $output);
        self::assertStringContainsString('ssl_session_cache', $output);
        self::assertStringContainsString('ssl_session_tickets', $output);
    }

    #[Test]
    public function it_includes_certificate_section(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('ssl_certificate', $output);
        self::assertStringContainsString('ssl_certificate_key', $output);
    }

    #[Test]
    public function it_excludes_http3_by_default(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringNotContainsString('HTTP/3', $output);
        self::assertStringNotContainsString('QUIC', $output);
        self::assertStringNotContainsString('Alt-Svc', $output);
    }

    #[Test]
    public function it_includes_http3_when_enabled(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate(http3: true);

        self::assertStringContainsString('HTTP/3 (QUIC)', $output);
        self::assertStringContainsString('Alt-Svc', $output);
        self::assertStringContainsString('UDP port 443', $output);
        self::assertStringContainsString('quic', $output);
    }

    #[Test]
    public function http3_section_includes_quic_settings(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate(http3: true);

        self::assertStringContainsString('quic_retry on', $output);
        self::assertStringContainsString('ssl_early_data on', $output);
    }

    #[Test]
    public function it_ends_with_newline(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringEndsWith("\n", $output);
    }

    #[Test]
    public function http3_output_also_ends_with_newline(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate(http3: true);

        self::assertStringEndsWith("\n", $output);
    }

    #[Test]
    public function it_includes_server_cipher_preference(): void
    {
        $generator = new TlsSnippetGenerator();

        $output = $generator->generate();

        self::assertStringContainsString('ssl_prefer_server_ciphers on', $output);
    }
}
