[package]
name = "pulsar-queue"
description = "Redis-backed job queue with msgpack serialisation and AEAD payload encryption."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pulsar-kernel = { path = "../pulsar-kernel", version = "=0.0.1-alpha.0" }
redis = { workspace = true }
rmp-serde = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
