<?php

declare(strict_types=1);

namespace Pulsar\Tests\Unit\Http\Validation;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Pulsar\Http\Validation\Violation;

#[CoversClass(Violation::class)]
final class ViolationTest extends TestCase
{
    #[Test]
    public function constructorSetsProperties(): void
    {
        $violation = new Violation(
            field: 'email',
            message: 'The email field is required.',
            rule: 'required',
        );

        self::assertSame('email', $violation->field);
        self::assertSame('The email field is required.', $violation->message);
        self::assertSame('required', $violation->rule);
        self::assertSame('VALIDATION_REQUIRED', $violation->code);
    }

    #[Test]
    public function toArrayReturnsStructuredArray(): void
    {
        $violation = new Violation(
            field: 'name',
            message: 'The name field must be a string.',
            rule: 'string',
        );

        self::assertSame([
            'field' => 'name',
            'message' => 'The name field must be a string.',
            'rule' => 'string',
            'code' => 'VALIDATION_STRING',
        ], $violation->toArray());
    }

    #[Test]
    public function codeAutoGeneratedFromRuleName(): void
    {
        $violation = new Violation(
            field: 'age',
            message: 'Must be an integer.',
            rule: 'integer',
        );

        self::assertSame('VALIDATION_INTEGER', $violation->code);
    }

    #[Test]
    public function explicitCodeOverridesDefault(): void
    {
        $violation = new Violation(
            field: 'email',
            message: 'Invalid email.',
            rule: 'email',
            code: 'CUSTOM_EMAIL_CODE',
        );

        self::assertSame('CUSTOM_EMAIL_CODE', $violation->code);
    }

    #[Test]
    public function backwardCompatibleWithThreeArgConstructor(): void
    {
        $violation = new Violation('field', 'message', 'rule');

        self::assertSame('field', $violation->field);
        self::assertSame('message', $violation->message);
        self::assertSame('rule', $violation->rule);
        self::assertSame('VALIDATION_RULE', $violation->code);
    }
}
