<?php

declare(strict_types=1);

namespace Pulsar\Extension\Grpc\Codegen;

use Pulsar\Api\Internal;
use RuntimeException;

use function file_put_contents;
use function implode;
use function is_dir;
use function mkdir;
use function preg_match;
use function preg_match_all;
use function sprintf;
use function str_replace;

/**
 * Generates Pulsar-specific service handler base classes from proto definitions.
 *
 * Reads the protoc-generated PHP files to discover service names and methods,
 * then generates abstract handler classes that implement ServiceHandlerInterface
 * with correctly typed method stubs.
 */
#[Internal(reason: 'Service handler code generation')]
final readonly class ServiceHandlerGenerator
{
    /**
     * Generate abstract handler classes from generated protoc output.
     *
     * @param list<string> $generatedFiles  The files generated by protoc
     * @param string $outputDir             Directory to write handler base classes
     * @param string $namespace             PHP namespace for generated handlers
     *
     * @return list<string> Paths to the generated handler files
     */
    public function generate(array $generatedFiles, string $outputDir, string $namespace): array
    {
        $services = $this->discoverServices($generatedFiles);
        $handlerFiles = [];

        foreach ($services as $service) {
            $filePath = $this->generateHandler($service, $outputDir, $namespace);
            $handlerFiles[] = $filePath;
        }

        return $handlerFiles;
    }

    /**
     * Discover protobuf service interfaces from generated files.
     *
     * Looks for files that contain gRPC client stubs generated by protoc's
     * gRPC plugin: these contain the service method signatures.
     *
     * @param list<string> $files
     *
     * @return list<ServiceInfo>
     */
    private function discoverServices(array $files): array
    {
        $services = [];

        foreach ($files as $file) {
            if (!file_exists($file)) {
                continue;
            }

            $content = file_get_contents($file);

            if ($content === false) {
                continue;
            }

            // Look for gRPC client stubs that extend \Grpc\BaseStub
            if (preg_match('/class\s+(\w+Client)\s+extends/', $content, $classMatch) !== 1) {
                continue;
            }

            $clientClass = $classMatch[1];
            $serviceName = str_replace('Client', '', $clientClass);

            // Extract namespace
            $serviceNamespace = '';
            if (preg_match('/namespace\s+([^;\s]+)\s*;/', $content, $nsMatch) === 1) {
                $serviceNamespace = $nsMatch[1];
            }

            // Extract method signatures
            $methods = $this->extractMethods($content);

            if ($methods !== []) {
                $services[] = new ServiceInfo(
                    name: $serviceName,
                    protoNamespace: $serviceNamespace,
                    methods: $methods,
                );
            }
        }

        return $services;
    }

    /**
     * Extract method definitions from a gRPC client stub.
     *
     * @return list<MethodInfo>
     */
    private function extractMethods(string $content): array
    {
        $methods = [];

        // Match public function methodName(\RequestType $argument, ...) patterns
        if (preg_match_all(
            '/public\s+function\s+(\w+)\s*\(\s*\\\\?([^$\s]+)\s+\$/',
            $content,
            $matches,
            PREG_SET_ORDER,
        ) === 0) {
            return [];
        }

        foreach ($matches as $match) {
            $methodName = $match[1];

            // Skip constructor and utility methods
            if ($methodName === '__construct' || $methodName === 'getChannel') {
                continue;
            }

            $inputType = '\\' . ltrim($match[2], '\\');

            $methods[] = new MethodInfo(
                name: $methodName,
                inputType: $inputType,
                outputType: $inputType, // Protoc stubs don't expose response type directly
            );
        }

        return $methods;
    }

    /**
     * Generate an abstract handler class for a service.
     */
    private function generateHandler(ServiceInfo $service, string $outputDir, string $namespace): string
    {
        $className = 'Abstract' . $service->name . 'Handler';
        $filePath = $outputDir . '/' . $className . '.php';

        if (!is_dir($outputDir) && !mkdir($outputDir, 0o755, true)) {
            throw new RuntimeException(sprintf('Cannot create output directory: %s', $outputDir));
        }

        $methodStubs = $this->generateMethodStubs($service->methods);
        $methodDescriptors = $this->generateMethodDescriptors($service);

        $protoServiceName = $service->protoNamespace !== ''
            ? str_replace('\\', '.', $service->protoNamespace) . '.' . $service->name
            : $service->name;

        $content = <<<PHP
            <?php

            declare(strict_types=1);

            namespace $namespace;

            use Pulsar\Extension\Grpc\Error\GrpcException;
            use Pulsar\Extension\Grpc\Error\GrpcStatus;
            use Pulsar\Extension\Grpc\Handler\MethodDescriptor;
            use Pulsar\Extension\Grpc\Handler\MethodType;
            use Pulsar\Extension\Grpc\Handler\ServiceHandlerInterface;

            /**
             * Abstract handler for the $service->name gRPC service.
             *
             * Generated from proto definitions. Implement the abstract methods
             * to provide your service logic.
             */
            abstract class $className implements ServiceHandlerInterface
            {
                public function serviceName(): string
                {
                    return '$protoServiceName';
                }

                public function methods(): array
                {
            $methodDescriptors
                }

                public function invoke(string \$method, string \$payload): string
                {
                    return match (\$method) {
            {$this->generateInvokeMatch($service->methods)}
                        default => throw new GrpcException(
                            GrpcStatus::Unimplemented,
                            'Method not implemented: ' . \$method,
                        ),
                    };
                }

            $methodStubs
            }

            PHP;

        file_put_contents($filePath, $content);

        return $filePath;
    }

    /**
     * Generate abstract method stubs for the handler.
     *
     * @param list<MethodInfo> $methods
     */
    private function generateMethodStubs(array $methods): string
    {
        $stubs = [];

        foreach ($methods as $method) {
            $stubs[] = <<<PHP
                    /**
                     * Handle the $method->name RPC.
                     *
                     * @param string \$payload Serialized protobuf request
                     *
                     * @return string Serialized protobuf response
                     */
                    abstract protected function handle$method->name(string \$payload): string;
                PHP;
        }

        return implode("\n\n", $stubs);
    }

    /**
     * Generate the method descriptors array for the methods() return.
     */
    private function generateMethodDescriptors(ServiceInfo $service): string
    {
        $lines = ['        return ['];

        $protoServiceName = $service->protoNamespace !== ''
            ? str_replace('\\', '.', $service->protoNamespace) . '.' . $service->name
            : $service->name;

        foreach ($service->methods as $method) {
            $fullName = '/' . $protoServiceName . '/' . $method->name;
            $lines[] = <<<PHP
                            '$method->name' => new MethodDescriptor(
                                name: '$method->name',
                                fullName: '$fullName',
                                type: MethodType::Unary,
                                inputType: '$method->inputType',
                                outputType: '$method->outputType',
                                handler: static::class . '::$method->name',
                            ),
                PHP;
        }

        $lines[] = '        ];';

        return implode("\n", $lines);
    }

    /**
     * Generate the match expression for invoke().
     *
     * @param list<MethodInfo> $methods
     */
    private function generateInvokeMatch(array $methods): string
    {
        $arms = [];

        foreach ($methods as $method) {
            $arms[] = sprintf(
                "            '%s' => \$this->handle%s(\$payload),",
                $method->name,
                $method->name,
            );
        }

        return implode("\n", $arms);
    }
}
